PYTHON ?= python3

.PHONY: medical_ai_safety_field_kit_global_safety_claim_review_workbook medical_ai_safety_field_kit_reviewer_sprint_board medical_ai_safety_field_kit_sfc005_synthetic_evidence_starter medical_ai_safety_field_kit_one_objection_gateway medical_ai_safety_field_kit_outside_reviewer_micro_brief

.PHONY: validate validate-public platform_dashboard public_safe_failure_cards turkiye_health_ai_safety_readiness_kit teknofest_health_ai_safety_addendum teknofest_health_ai_detail_report_final_gate turkiye_health_data_steward_scout turkiye_health_ai_funding_route_fit_memo tuseb_a4_um_medical_ai_safety_concept_gate tuseb_route_fit_question_packet tuseb_a4_um_tuyze_non_patient_data_concept_note turkiye_health_ai_safety_handoff_index turkiye_health_ai_safety_follow_up_decision_gate global_health_ai_opportunity_radar eu_ai_act_health_ai_sandbox_readiness_crosswalk medhelm_healthbench_bridge_compatibility_note chai_governance_companion_note hospital_ai_governance_intake_worksheet no_ranking_benchmark_misuse_warning benchmark_language_reviewer_handoff_card turkiye_clinical_ai_assurance_lab_readiness_matrix hospital_ai_literacy_collaboration_packet route_owner_acknowledgement_follow_up_decision_memo tuseb_a4_um_30_june_decision_sprint tuseb_a4_um_eligibility_authority_lock tuseb_a4_um_go_no_go_packet tuseb_a4_um_private_decision_checklist tuseb_a4_um_private_evidence_closure_note medical_ai_post_0900_priority_reset global_benchmark_pressure_response failure_atlas_real_clinical_text_pressure_template sourcecheckup_medical_benchmark_source_support_worksheet turkish_medical_llm_coverage_pressure_addendum turkish_medical_llm_coverage_reviewer_intake_rows turkish_medical_llm_reviewer_issue_template turkish_medical_llm_issue_triage_examples sourcecheckup_medical_turkish_source_support_examples sourcecheckup_medical_turkish_language_source_support_dashboard sourcecheckup_medical_turkish_release_gate_row_pack sourcecheckup_medical_turkish_release_gate_outcome_examples sourcecheckup_medical_turkish_release_note_closure_checklist sourcecheckup_medical_turkish_maintainer_handoff_digest sourcecheckup_medical_turkish_maintainer_digest_index_card medical_ai_safety_field_kit_public_objection_intake field_impact_packages tubitak_1711_ai_assurance_sidecar tubitak_1711_consortium_readiness_no_partner_gate named_outreach_decision_matrix field_opportunity_decision_packages goktug_field_action_review_packet teknofest_public_share_clearance_packet current_medical_ai_intelligence_priority_update turkiye_ai_ethics_status_gate_note tr_clinical_ai_assurance_sandbox_readiness_gate sourcecheckup_medical_benchmark_boundary_delta paired_sandbox_boundary_delta clinician_ai_literacy_sandbox_handoff_micro_module sourcecheckup_medical_source_support_delta_queue paired_literacy_source_support_delta sourcecheckup sourcecheckup_v02 sourcecheckup_contrib_v02 sourcecheckup_public_issue sourcecheckup_repo_run_guide healthbench_medhelm_mapping benchmark_reviewer_questions reviewer_question_issue_templates reviewer_question_intake_examples reviewer_question_intake_triage reviewer_question_wording_log reviewer_question_release_gates reviewer_question_gate_outcomes reviewer_question_release_packet reviewer_question_changelog reviewer_question_release_index reviewer_question_contributor_digest reviewer_question_maintainer_handoff reviewer_question_maintainer_closeout_digest reviewer_question_maintainer_release_readiness_digest reviewer_question_maintainer_evidence_map reviewer_question_maintainer_audit_trail_packet reviewer_question_maintainer_release_candidate_summary reviewer_question_maintainer_public_preview_decision_log reviewer_question_maintainer_public_preview_handoff_summary reviewer_question_maintainer_public_preview_closure_checklist reviewer_question_maintainer_public_preview_archive_digest reviewer_question_maintainer_public_preview_index_rollup reviewer_question_maintainer_public_preview_repository_navigation_note reviewer_question_maintainer_public_preview_release_card reviewer_question_maintainer_public_preview_contributor_route_note reviewer_question_maintainer_public_preview_issue_template_route_note reviewer_question_maintainer_public_preview_maintainer_acceptance_checklist reviewer_question_maintainer_public_preview_acceptance_closeout_digest reviewer_question_maintainer_public_preview_acceptance_archive_index reviewer_question_maintainer_public_preview_acceptance_archive_release_note reviewer_question_maintainer_public_preview_acceptance_archive_closure_note reviewer_question_maintainer_public_preview_acceptance_archive_final_index reviewer_question_maintainer_public_preview_acceptance_archive_handoff_packet reviewer_question_maintainer_public_preview_acceptance_archive_steward_note reviewer_question_maintainer_public_preview_acceptance_archive_steward_index reviewer_question_maintainer_public_preview_acceptance_archive_stewardship_closeout reviewer_question_maintainer_public_preview_acceptance_archive_stewardship_digest reviewer_question_maintainer_public_preview_acceptance_archive_public_handoff_note reviewer_question_maintainer_public_preview_acceptance_archive_public_handoff_digest reviewer_question_maintainer_public_preview_acceptance_archive_public_handoff_release_index reviewer_question_maintainer_public_preview_acceptance_archive_public_handoff_release_note reviewer_question_maintainer_public_preview_acceptance_archive_public_handoff_closure_note label_audit_public_issue label_audit_examples label_audit_dashboard label_audit_triage label_audit_wording_log label_audit_release_gates label_audit_outcome_dashboard label_audit_release_packet label_audit_changelog label_audit_release_index label_audit_contributor_digest label_audit_maintainer_handoff label_audit_maintainer_closeout_digest label_audit_maintainer_release_readiness_digest label_audit_maintainer_evidence_map label_audit_maintainer_audit_trail_packet label_audit_maintainer_release_candidate_summary label_audit_maintainer_public_preview_decision_log label_audit_maintainer_public_preview_handoff_summary label_audit_maintainer_public_preview_closure_checklist sourcecheckup_expansion_dashboard sourcecheckup_tr_medllm_routing sourcecheckup_turkish_institutional_wording source_review_worksheets red_flag_warning_checklist red_flag_contributor_examples warning_sign_role_table label_audit_role_table bilge_readiness_queue tubitak_1711_readiness_packet source_claim_queue health_data_quality_card boundary_notes assurance_card_template assurance_release_gate_map clinician_literacy_map tr_medllm_specialty_spread tr_medllm_specialty_dashboard leaderboard leaderboard_report case_intake taxonomy_dashboard tr_medllm_pack clinician_review_queue clinician_review_protocol release_note

validate:
	$(PYTHON) scripts/validate_external_sample_jsonl.py data/failure_atlas_external_sample_v0_1.jsonl
	$(PYTHON) scripts/validate_medhelm_metric_json.py data/medhelm_remote_rescue_metric_v0_1.json
	$(PYTHON) scripts/validate_scoring_rubric_v0_1.py
	$(PYTHON) scripts/validate_failure_atlas_public_summary_v0_1.py
	$(PYTHON) scripts/validate_clinician_review_protocol_v0_1.py
	$(PYTHON) scripts/validate_source_claim_review_queue_v0_1.py
	$(PYTHON) scripts/validate_sourcecheckup_public_contributor_issue_v0_1.py
	$(PYTHON) scripts/validate_label_audit_public_contributor_issue_v0_1.py
	$(PYTHON) scripts/validate_label_audit_example_intake_v0_1.py
	$(PYTHON) scripts/validate_label_audit_example_dashboard_v0_1.py
	$(PYTHON) scripts/validate_label_audit_maintainer_triage_board_v0_1.py
	$(PYTHON) scripts/validate_label_audit_public_wording_decision_log_v0_1.py
	$(PYTHON) scripts/validate_label_audit_release_gate_checklist_v0_1.py
	$(PYTHON) scripts/validate_label_audit_release_gate_outcome_dashboard_v0_1.py
	$(PYTHON) scripts/validate_label_audit_release_note_packet_v0_1.py
	$(PYTHON) scripts/validate_label_audit_public_changelog_v0_1.py
	$(PYTHON) scripts/validate_label_audit_public_release_index_v0_1.py
	$(PYTHON) scripts/validate_label_audit_public_contributor_digest_v0_1.py
	$(PYTHON) scripts/validate_label_audit_maintainer_handoff_notes_v0_1.py
	$(PYTHON) scripts/validate_label_audit_maintainer_closeout_digest_v0_1.py
	$(PYTHON) scripts/validate_label_audit_maintainer_release_readiness_digest_v0_1.py
	$(PYTHON) scripts/validate_label_audit_maintainer_evidence_map_v0_1.py
	$(PYTHON) scripts/validate_label_audit_maintainer_audit_trail_packet_v0_1.py
	$(PYTHON) scripts/validate_label_audit_maintainer_release_candidate_summary_v0_1.py
	$(PYTHON) scripts/validate_label_audit_maintainer_public_preview_decision_log_v0_1.py
	$(PYTHON) scripts/validate_label_audit_maintainer_public_preview_handoff_summary_v0_1.py
	$(PYTHON) scripts/validate_label_audit_maintainer_public_preview_closure_checklist_v0_1.py
	$(PYTHON) scripts/validate_bilge_readiness_queue_v0_1.py
	$(PYTHON) scripts/validate_tubitak_1711_collaboration_readiness_packet_v0_1.py
	$(PYTHON) scripts/validate_sourcecheckup_contribution_v0_2.py
	$(PYTHON) scripts/validate_red_flag_contributor_examples_v0_1.py
	$(PYTHON) scripts/validate_sourcecheckup_turkish_institutional_wording_examples_v0_1.py
	$(PYTHON) scripts/validate_sourcecheckup_repo_run_guide_v0_1.py
	$(PYTHON) scripts/validate_healthbench_medhelm_mapping_note_v0_1.py
	$(PYTHON) scripts/validate_tr_clinical_ai_assurance_sandbox_readiness_gate_checklist_v0_1.py
	$(PYTHON) scripts/validate_sourcecheckup_medical_benchmark_boundary_delta_note_v0_1.py
	$(PYTHON) scripts/validate_clinician_ai_literacy_sandbox_handoff_micro_module_v0_1.py
	$(PYTHON) scripts/validate_sourcecheckup_medical_source_support_delta_queue_v0_1.py
	$(PYTHON) scripts/validate_turkiye_health_ai_safety_readiness_kit_20260618.py
	$(PYTHON) scripts/validate_teknofest_health_ai_safety_addendum_20260618.py
	$(PYTHON) scripts/validate_tubitak_1711_ai_assurance_sidecar_20260618.py
	$(PYTHON) scripts/validate_tubitak_1711_consortium_readiness_no_partner_gate_20260619.py
	$(PYTHON) scripts/validate_medical_ai_safety_field_kit_reviewer_start_here_20260619.py
	$(PYTHON) scripts/validate_medical_ai_safety_field_kit_global_safety_claim_review_workbook_20260620.py
	$(PYTHON) scripts/validate_medical_ai_safety_field_kit_reviewer_sprint_board_20260620.py
	$(PYTHON) scripts/validate_medical_ai_safety_field_kit_external_route_scout_board_20260620.py
	$(PYTHON) scripts/validate_medical_ai_safety_field_kit_sfc005_synthetic_evidence_starter_20260620.py
	$(PYTHON) scripts/validate_medical_ai_safety_field_kit_one_objection_gateway_20260620.py
	$(PYTHON) scripts/validate_medical_ai_safety_field_kit_outside_reviewer_micro_brief_20260620.py
	$(PYTHON) scripts/validate_medical_ai_safety_field_kit_public_call_20260619.py
	$(PYTHON) scripts/validate_medical_ai_safety_field_kit_target_distribution_index_20260619.py
	$(PYTHON) scripts/validate_medical_ai_safety_field_kit_send_approval_packet_20260619.py
	$(PYTHON) scripts/validate_medical_ai_safety_field_kit_public_objection_ledger_20260619.py
	$(PYTHON) scripts/validate_medical_ai_safety_field_kit_public_objection_intake_20260619.py
	$(PYTHON) scripts/validate_tubitak_1711_smart_education_fit_gate_20260618.py
	$(PYTHON) scripts/validate_tubitak_1711_smart_education_named_scout_20260618.py
	$(PYTHON) scripts/validate_tubitak_1711_sebit_route_owner_scout_20260618.py
	$(PYTHON) scripts/validate_tubitak_1711_acibadem_case_demand_side_scout_20260618.py
	$(PYTHON) scripts/validate_tuyze_education_route_owner_scout_20260618.py
	$(PYTHON) scripts/validate_tubitak_1711_three_gate_consortium_fit_map_20260618.py
	$(PYTHON) scripts/validate_deu_digital_medicine_board_route_owner_scout_20260618.py
	$(PYTHON) scripts/validate_ktu_ai_simulation_congress_route_owner_scout_20260618.py
	$(PYTHON) scripts/validate_turkiye_health_ai_safety_route_owner_map_20260618.py
	$(PYTHON) scripts/validate_turkiye_health_ai_safety_field_readiness_dashboard_20260618.py
	$(PYTHON) scripts/validate_turkiye_clinician_ai_safety_mini_curriculum_20260618.py
	$(PYTHON) scripts/validate_turkiye_no_ranking_medical_ai_assurance_card_20260618.py
	$(PYTHON) scripts/validate_teknofest_health_ai_detail_report_final_gate_20260618.py
	$(PYTHON) scripts/validate_turkiye_health_data_steward_scout_20260618.py
	$(PYTHON) scripts/validate_turkiye_health_ai_funding_route_fit_memo_20260618.py
	$(PYTHON) scripts/validate_tuseb_a4_um_medical_ai_safety_concept_gate_20260619.py
	$(PYTHON) scripts/validate_tuseb_route_fit_question_packet_20260619.py
	$(PYTHON) scripts/validate_tuseb_a4_um_tuyze_non_patient_data_concept_note_20260619.py
	$(PYTHON) scripts/validate_turkiye_health_ai_safety_handoff_index_20260619.py
	$(PYTHON) scripts/validate_turkiye_health_ai_safety_follow_up_decision_gate_20260619.py
	$(PYTHON) scripts/validate_global_health_ai_opportunity_radar_20260619.py
	$(PYTHON) scripts/validate_eu_ai_act_health_ai_sandbox_readiness_crosswalk_20260619.py
	$(PYTHON) scripts/validate_medhelm_healthbench_bridge_compatibility_note_20260619.py
	$(PYTHON) scripts/validate_chai_governance_companion_note_20260619.py
	$(PYTHON) scripts/validate_hospital_ai_governance_intake_worksheet_20260619.py
	$(PYTHON) scripts/validate_no_ranking_benchmark_misuse_warning_20260619.py
	$(PYTHON) scripts/validate_benchmark_language_reviewer_handoff_card_20260619.py
	$(PYTHON) scripts/validate_turkiye_clinical_ai_assurance_lab_readiness_matrix_20260619.py
	$(PYTHON) scripts/validate_hospital_ai_literacy_collaboration_packet_20260619.py
	$(PYTHON) scripts/validate_route_owner_acknowledgement_follow_up_decision_memo_20260619.py
	$(PYTHON) scripts/validate_tuseb_a4_um_30_june_decision_sprint_20260619.py
	$(PYTHON) scripts/validate_tuseb_a4_um_eligibility_authority_lock_20260619.py
	$(PYTHON) scripts/validate_tuseb_a4_um_go_no_go_packet_20260619.py
	$(PYTHON) scripts/validate_tuseb_a4_um_private_decision_checklist_20260619.py
	$(PYTHON) scripts/validate_tuseb_a4_um_private_evidence_closure_note_20260619.py
	$(PYTHON) scripts/validate_medical_ai_post_0900_priority_reset_20260619.py
	$(PYTHON) scripts/validate_global_benchmark_pressure_response_20260619.py
	$(PYTHON) scripts/validate_failure_atlas_real_clinical_text_pressure_template_20260619.py
	$(PYTHON) scripts/validate_sourcecheckup_medical_benchmark_source_support_worksheet_20260619.py
	$(PYTHON) scripts/validate_turkish_medical_llm_coverage_pressure_addendum_20260619.py
	$(PYTHON) scripts/validate_turkish_medical_llm_coverage_reviewer_intake_rows_20260619.py
	$(PYTHON) scripts/validate_turkish_medical_llm_reviewer_issue_template_20260619.py
	$(PYTHON) scripts/validate_turkish_medical_llm_issue_triage_examples_20260619.py
	$(PYTHON) scripts/validate_sourcecheckup_medical_turkish_source_support_examples_20260619.py
	$(PYTHON) scripts/validate_sourcecheckup_medical_turkish_language_source_support_dashboard_20260619.py
	$(PYTHON) scripts/validate_sourcecheckup_medical_turkish_release_gate_row_pack_20260619.py
	$(PYTHON) scripts/validate_sourcecheckup_medical_turkish_release_gate_outcome_examples_20260619.py
	$(PYTHON) scripts/validate_sourcecheckup_medical_turkish_release_note_closure_checklist_20260619.py
	$(PYTHON) scripts/validate_sourcecheckup_medical_turkish_maintainer_handoff_digest_20260619.py
	$(PYTHON) scripts/validate_sourcecheckup_medical_turkish_maintainer_digest_index_card_20260619.py
	$(PYTHON) scripts/validate_named_outreach_decision_matrix_20260618.py
	$(PYTHON) scripts/validate_goktug_field_action_review_packet_20260618.py
	$(PYTHON) scripts/validate_teknofest_public_share_clearance_packet_20260618.py
	$(PYTHON) scripts/validate_tuyze_health_ai_safety_readiness_companion_20260618.py
	$(PYTHON) scripts/validate_turkiye_health_ai_safety_outreach_roadmap_20260618.py
	$(PYTHON) scripts/validate_hospital_medical_faculty_outreach_draft_20260618.py
	$(PYTHON) scripts/validate_hacettepe_health_informatics_outreach_packet_20260618.py
	$(PYTHON) scripts/validate_hacettepe_health_management_ai_outreach_packet_20260618.py
	$(PYTHON) scripts/validate_acibadem_medical_ethics_ai_outreach_packet_20260618.py
	$(PYTHON) scripts/validate_benchmark_style_reviewer_questions_v0_1.py
	$(PYTHON) scripts/validate_benchmark_reviewer_question_issue_templates_v0_1.py
	$(PYTHON) scripts/validate_reviewer_question_intake_examples_v0_1.py
	$(PYTHON) scripts/validate_reviewer_question_intake_triage_board_v0_1.py
	$(PYTHON) scripts/validate_reviewer_question_public_wording_decision_log_v0_1.py
	$(PYTHON) scripts/validate_reviewer_question_release_gate_checklist_v0_1.py
	$(PYTHON) scripts/validate_reviewer_question_release_gate_outcome_dashboard_v0_1.py
	$(PYTHON) scripts/validate_reviewer_question_public_release_packet_v0_1.py
	$(PYTHON) scripts/validate_reviewer_question_public_changelog_v0_1.py
	$(PYTHON) scripts/validate_reviewer_question_public_release_index_v0_1.py
	$(PYTHON) scripts/validate_reviewer_question_public_contributor_digest_v0_1.py
	$(PYTHON) scripts/validate_reviewer_question_maintainer_handoff_notes_v0_1.py
	$(PYTHON) scripts/validate_reviewer_question_maintainer_closeout_digest_v0_1.py
	$(PYTHON) scripts/validate_reviewer_question_maintainer_release_readiness_digest_v0_1.py
	$(PYTHON) scripts/validate_reviewer_question_maintainer_evidence_map_v0_1.py
	$(PYTHON) scripts/validate_reviewer_question_maintainer_audit_trail_packet_v0_1.py
	$(PYTHON) scripts/validate_reviewer_question_maintainer_release_candidate_summary_v0_1.py
	$(PYTHON) scripts/validate_reviewer_question_maintainer_public_preview_decision_log_v0_1.py
	$(PYTHON) scripts/validate_reviewer_question_maintainer_public_preview_handoff_summary_v0_1.py
	$(PYTHON) scripts/validate_reviewer_question_maintainer_public_preview_closure_checklist_v0_1.py
	$(PYTHON) scripts/validate_reviewer_question_maintainer_public_preview_archive_digest_v0_1.py
	$(PYTHON) scripts/validate_reviewer_question_maintainer_public_preview_index_rollup_v0_1.py
	$(PYTHON) scripts/validate_reviewer_question_maintainer_public_preview_repository_navigation_note_v0_1.py
	$(PYTHON) scripts/validate_reviewer_question_maintainer_public_preview_release_card_v0_1.py
	$(PYTHON) scripts/validate_reviewer_question_maintainer_public_preview_contributor_route_note_v0_1.py
	$(PYTHON) scripts/validate_reviewer_question_maintainer_public_preview_issue_template_route_note_v0_1.py
	$(PYTHON) scripts/validate_reviewer_question_maintainer_public_preview_maintainer_acceptance_checklist_v0_1.py
	$(PYTHON) scripts/validate_reviewer_question_maintainer_public_preview_acceptance_closeout_digest_v0_1.py
	$(PYTHON) scripts/validate_reviewer_question_maintainer_public_preview_acceptance_archive_index_v0_1.py
	$(PYTHON) scripts/validate_reviewer_question_maintainer_public_preview_acceptance_archive_release_note_v0_1.py
	$(PYTHON) scripts/validate_reviewer_question_maintainer_public_preview_acceptance_archive_closure_note_v0_1.py
	$(PYTHON) scripts/validate_reviewer_question_maintainer_public_preview_acceptance_archive_final_index_v0_1.py
	$(PYTHON) scripts/validate_reviewer_question_maintainer_public_preview_acceptance_archive_handoff_packet_v0_1.py
	$(PYTHON) scripts/validate_reviewer_question_maintainer_public_preview_acceptance_archive_steward_note_v0_1.py
	$(PYTHON) scripts/validate_reviewer_question_maintainer_public_preview_acceptance_archive_steward_index_v0_1.py
	$(PYTHON) scripts/validate_reviewer_question_maintainer_public_preview_acceptance_archive_stewardship_closeout_v0_1.py
	$(PYTHON) scripts/validate_reviewer_question_maintainer_public_preview_acceptance_archive_stewardship_digest_v0_1.py
	$(PYTHON) scripts/validate_reviewer_question_maintainer_public_preview_acceptance_archive_public_handoff_note_v0_1.py
	$(PYTHON) scripts/validate_reviewer_question_maintainer_public_preview_acceptance_archive_public_handoff_digest_v0_1.py
	$(PYTHON) scripts/validate_reviewer_question_maintainer_public_preview_acceptance_archive_public_handoff_release_index_v0_1.py
	$(PYTHON) scripts/validate_reviewer_question_maintainer_public_preview_acceptance_archive_public_handoff_release_note_v0_1.py
	$(PYTHON) scripts/validate_reviewer_question_maintainer_public_preview_acceptance_archive_public_handoff_closure_note_v0_1.py
	$(PYTHON) scripts/validate_current_medical_ai_intelligence_priority_update_20260618_v0_1.py
	$(PYTHON) scripts/validate_turkiye_ai_ethics_status_gate_note_v0_1.py
	$(PYTHON) scripts/validate_sourcecheckup_example_expansion_dashboard_v0_2.py
	$(PYTHON) scripts/validate_sourcecheckup_medical_source_claim_walkthrough_v0_1.py
	$(PYTHON) scripts/validate_public_safe_failure_cards_20260619.py
	$(PYTHON) scripts/validate_safe_failure_card_issue_template_20260619.py
	$(PYTHON) scripts/validate_health_data_quality_card_v0_1.py
	$(PYTHON) scripts/validate_boundary_notes_v0_1.py
	$(PYTHON) scripts/validate_assurance_card_template_v0_1.py
	$(PYTHON) scripts/validate_assurance_release_gate_example_map_v0_1.py
	$(PYTHON) scripts/validate_clinician_literacy_release_gate_lesson_map_v0_1.py
	$(PYTHON) scripts/validate_sourcecheckup_tr_medllm_assurance_routing_map_v0_1.py
	$(PYTHON) scripts/validate_source_review_worksheets_v0_1.py
	$(PYTHON) scripts/validate_red_flag_warning_checklist_v0_1.py
	$(PYTHON) scripts/validate_tr_medllm_specialty_spread_v0_1.py
	$(PYTHON) scripts/validate_warning_sign_reviewer_role_table_v0_1.py
	$(PYTHON) scripts/validate_label_audit_reviewer_role_table_v0_1.py
	$(PYTHON) scripts/validate_tr_medllm_specialty_dashboard_v0_1.py
	$(PYTHON) scripts/validate_platform_dashboard_index_v0_1.py
	$(PYTHON) scripts/validate_public_release_note_v0_1.py
	find . -type d -name __pycache__ -prune -exec rm -rf {} +
	find . -type f \( -name '*.pyc' -o -name '*.pyo' \) -delete
	$(PYTHON) scripts/validate_public_release.py --root .

validate-public: validate

platform_dashboard:
	$(PYTHON) scripts/validate_platform_dashboard_index_v0_1.py

public_safe_failure_cards:
	$(PYTHON) scripts/validate_public_safe_failure_cards_20260619.py

safe_failure_card_issue_template:
	$(PYTHON) scripts/validate_safe_failure_card_issue_template_20260619.py

.PHONY: medical_ai_safety_field_kit_reviewer_start_here
medical_ai_safety_field_kit_reviewer_start_here:
	$(PYTHON) scripts/validate_medical_ai_safety_field_kit_reviewer_start_here_20260619.py

medical_ai_safety_field_kit_global_safety_claim_review_workbook:
	$(PYTHON) scripts/validate_medical_ai_safety_field_kit_global_safety_claim_review_workbook_20260620.py

medical_ai_safety_field_kit_reviewer_sprint_board:
	$(PYTHON) scripts/validate_medical_ai_safety_field_kit_reviewer_sprint_board_20260620.py

medical_ai_safety_field_kit_external_route_scout_board:
	$(PYTHON) scripts/validate_medical_ai_safety_field_kit_external_route_scout_board_20260620.py

medical_ai_safety_field_kit_sfc005_synthetic_evidence_starter:
	$(PYTHON) scripts/validate_medical_ai_safety_field_kit_sfc005_synthetic_evidence_starter_20260620.py

medical_ai_safety_field_kit_one_objection_gateway:
	$(PYTHON) scripts/validate_medical_ai_safety_field_kit_one_objection_gateway_20260620.py

medical_ai_safety_field_kit_outside_reviewer_micro_brief:
	$(PYTHON) scripts/validate_medical_ai_safety_field_kit_outside_reviewer_micro_brief_20260620.py

turkiye_health_ai_safety_readiness_kit:
	$(PYTHON) scripts/generate_turkiye_health_ai_safety_readiness_kit_20260618.py
	$(PYTHON) scripts/validate_turkiye_health_ai_safety_readiness_kit_20260618.py

teknofest_health_ai_safety_addendum:
	$(PYTHON) scripts/generate_teknofest_health_ai_safety_addendum_20260618.py
	$(PYTHON) scripts/validate_teknofest_health_ai_safety_addendum_20260618.py

teknofest_health_ai_detail_report_final_gate:
	$(PYTHON) scripts/validate_teknofest_health_ai_detail_report_final_gate_20260618.py

turkiye_health_data_steward_scout:
	$(PYTHON) scripts/validate_turkiye_health_data_steward_scout_20260618.py

turkiye_health_ai_funding_route_fit_memo:
	$(PYTHON) scripts/validate_turkiye_health_ai_funding_route_fit_memo_20260618.py

tuseb_a4_um_medical_ai_safety_concept_gate:
	$(PYTHON) scripts/validate_tuseb_a4_um_medical_ai_safety_concept_gate_20260619.py

tuseb_route_fit_question_packet:
	$(PYTHON) scripts/validate_tuseb_route_fit_question_packet_20260619.py

tuseb_a4_um_tuyze_non_patient_data_concept_note:
	$(PYTHON) scripts/validate_tuseb_a4_um_tuyze_non_patient_data_concept_note_20260619.py

turkiye_health_ai_safety_handoff_index:
	$(PYTHON) scripts/validate_turkiye_health_ai_safety_handoff_index_20260619.py

turkiye_health_ai_safety_follow_up_decision_gate:
	$(PYTHON) scripts/validate_turkiye_health_ai_safety_follow_up_decision_gate_20260619.py

global_health_ai_opportunity_radar:
	$(PYTHON) scripts/validate_global_health_ai_opportunity_radar_20260619.py

eu_ai_act_health_ai_sandbox_readiness_crosswalk:
	$(PYTHON) scripts/validate_eu_ai_act_health_ai_sandbox_readiness_crosswalk_20260619.py

medhelm_healthbench_bridge_compatibility_note:
	$(PYTHON) scripts/validate_medhelm_healthbench_bridge_compatibility_note_20260619.py

chai_governance_companion_note:
	$(PYTHON) scripts/validate_chai_governance_companion_note_20260619.py

hospital_ai_governance_intake_worksheet:
	$(PYTHON) scripts/validate_hospital_ai_governance_intake_worksheet_20260619.py

no_ranking_benchmark_misuse_warning:
	$(PYTHON) scripts/validate_no_ranking_benchmark_misuse_warning_20260619.py

benchmark_language_reviewer_handoff_card:
	$(PYTHON) scripts/validate_benchmark_language_reviewer_handoff_card_20260619.py

turkiye_clinical_ai_assurance_lab_readiness_matrix:
	$(PYTHON) scripts/validate_turkiye_clinical_ai_assurance_lab_readiness_matrix_20260619.py

hospital_ai_literacy_collaboration_packet:
	$(PYTHON) scripts/validate_hospital_ai_literacy_collaboration_packet_20260619.py

route_owner_acknowledgement_follow_up_decision_memo:
	$(PYTHON) scripts/validate_route_owner_acknowledgement_follow_up_decision_memo_20260619.py

tuseb_a4_um_30_june_decision_sprint:
	$(PYTHON) scripts/validate_tuseb_a4_um_30_june_decision_sprint_20260619.py

tuseb_a4_um_eligibility_authority_lock:
	$(PYTHON) scripts/validate_tuseb_a4_um_eligibility_authority_lock_20260619.py

tuseb_a4_um_go_no_go_packet:
	$(PYTHON) scripts/validate_tuseb_a4_um_go_no_go_packet_20260619.py

medical_ai_post_0900_priority_reset:
	$(PYTHON) scripts/validate_medical_ai_post_0900_priority_reset_20260619.py

global_benchmark_pressure_response:
	$(PYTHON) scripts/validate_global_benchmark_pressure_response_20260619.py

failure_atlas_real_clinical_text_pressure_template:
	$(PYTHON) scripts/validate_failure_atlas_real_clinical_text_pressure_template_20260619.py

sourcecheckup_medical_benchmark_source_support_worksheet:
	$(PYTHON) scripts/validate_sourcecheckup_medical_benchmark_source_support_worksheet_20260619.py

turkish_medical_llm_coverage_pressure_addendum:
	$(PYTHON) scripts/validate_turkish_medical_llm_coverage_pressure_addendum_20260619.py

turkish_medical_llm_coverage_reviewer_intake_rows:
	$(PYTHON) scripts/validate_turkish_medical_llm_coverage_reviewer_intake_rows_20260619.py

turkish_medical_llm_reviewer_issue_template:
	$(PYTHON) scripts/validate_turkish_medical_llm_reviewer_issue_template_20260619.py

turkish_medical_llm_issue_triage_examples:
	$(PYTHON) scripts/validate_turkish_medical_llm_issue_triage_examples_20260619.py

sourcecheckup_medical_turkish_source_support_examples:
	$(PYTHON) scripts/validate_sourcecheckup_medical_turkish_source_support_examples_20260619.py

sourcecheckup_medical_turkish_language_source_support_dashboard:
	$(PYTHON) scripts/validate_sourcecheckup_medical_turkish_language_source_support_dashboard_20260619.py

sourcecheckup_medical_turkish_release_gate_row_pack:
	$(PYTHON) scripts/validate_sourcecheckup_medical_turkish_release_gate_row_pack_20260619.py

sourcecheckup_medical_turkish_release_gate_outcome_examples:
	$(PYTHON) scripts/validate_sourcecheckup_medical_turkish_release_gate_outcome_examples_20260619.py

sourcecheckup_medical_turkish_release_note_closure_checklist:
	$(PYTHON) scripts/validate_sourcecheckup_medical_turkish_release_note_closure_checklist_20260619.py

sourcecheckup_medical_turkish_maintainer_handoff_digest:
	$(PYTHON) scripts/validate_sourcecheckup_medical_turkish_maintainer_handoff_digest_20260619.py

sourcecheckup_medical_turkish_maintainer_digest_index_card:
	$(PYTHON) scripts/validate_sourcecheckup_medical_turkish_maintainer_digest_index_card_20260619.py

tuseb_a4_um_private_decision_checklist:
	$(PYTHON) scripts/validate_tuseb_a4_um_private_decision_checklist_20260619.py

tuseb_a4_um_private_evidence_closure_note:
	$(PYTHON) scripts/validate_tuseb_a4_um_private_evidence_closure_note_20260619.py

field_impact_packages: turkiye_health_ai_safety_readiness_kit teknofest_health_ai_safety_addendum teknofest_health_ai_detail_report_final_gate turkiye_health_data_steward_scout turkiye_health_ai_funding_route_fit_memo tuseb_a4_um_medical_ai_safety_concept_gate tuseb_route_fit_question_packet tuseb_a4_um_tuyze_non_patient_data_concept_note turkiye_health_ai_safety_handoff_index turkiye_health_ai_safety_follow_up_decision_gate global_health_ai_opportunity_radar eu_ai_act_health_ai_sandbox_readiness_crosswalk medhelm_healthbench_bridge_compatibility_note chai_governance_companion_note hospital_ai_governance_intake_worksheet no_ranking_benchmark_misuse_warning benchmark_language_reviewer_handoff_card turkiye_clinical_ai_assurance_lab_readiness_matrix hospital_ai_literacy_collaboration_packet route_owner_acknowledgement_follow_up_decision_memo tuseb_a4_um_30_june_decision_sprint tuseb_a4_um_eligibility_authority_lock tuseb_a4_um_go_no_go_packet tuseb_a4_um_private_decision_checklist tuseb_a4_um_private_evidence_closure_note medical_ai_post_0900_priority_reset global_benchmark_pressure_response failure_atlas_real_clinical_text_pressure_template sourcecheckup_medical_benchmark_source_support_worksheet turkish_medical_llm_coverage_pressure_addendum turkish_medical_llm_coverage_reviewer_intake_rows turkish_medical_llm_reviewer_issue_template turkish_medical_llm_issue_triage_examples sourcecheckup_medical_turkish_source_support_examples sourcecheckup_medical_turkish_language_source_support_dashboard sourcecheckup_medical_turkish_release_gate_row_pack sourcecheckup_medical_turkish_release_gate_outcome_examples sourcecheckup_medical_turkish_release_note_closure_checklist sourcecheckup_medical_turkish_maintainer_handoff_digest sourcecheckup_medical_turkish_maintainer_digest_index_card

tubitak_1711_ai_assurance_sidecar:
	$(PYTHON) scripts/generate_tubitak_1711_ai_assurance_sidecar_20260618.py
	$(PYTHON) scripts/validate_tubitak_1711_ai_assurance_sidecar_20260618.py

tubitak_1711_consortium_readiness_no_partner_gate:
	$(PYTHON) scripts/generate_tubitak_1711_consortium_readiness_no_partner_gate_20260619.py
	$(PYTHON) scripts/validate_tubitak_1711_consortium_readiness_no_partner_gate_20260619.py

medical_ai_safety_field_kit_public_call:
	$(PYTHON) scripts/generate_medical_ai_safety_field_kit_public_call_20260619.py
	$(PYTHON) scripts/validate_medical_ai_safety_field_kit_public_call_20260619.py

medical_ai_safety_field_kit_target_distribution_index:
	$(PYTHON) scripts/generate_medical_ai_safety_field_kit_target_distribution_index_20260619.py
	$(PYTHON) scripts/validate_medical_ai_safety_field_kit_target_distribution_index_20260619.py

medical_ai_safety_field_kit_send_approval_packet:
	$(PYTHON) scripts/generate_medical_ai_safety_field_kit_send_approval_packet_20260619.py
	$(PYTHON) scripts/validate_medical_ai_safety_field_kit_send_approval_packet_20260619.py

medical_ai_safety_field_kit_public_objection_ledger:
	$(PYTHON) scripts/generate_medical_ai_safety_field_kit_public_objection_ledger_20260619.py
	$(PYTHON) scripts/validate_medical_ai_safety_field_kit_public_objection_ledger_20260619.py

medical_ai_safety_field_kit_public_objection_intake:
	$(PYTHON) scripts/generate_medical_ai_safety_field_kit_public_objection_intake_20260619.py
	$(PYTHON) scripts/validate_medical_ai_safety_field_kit_public_objection_intake_20260619.py

tubitak_1711_smart_education_fit_gate:
	$(PYTHON) scripts/validate_tubitak_1711_smart_education_fit_gate_20260618.py

tubitak_1711_smart_education_named_scout:
	$(PYTHON) scripts/validate_tubitak_1711_smart_education_named_scout_20260618.py

tubitak_1711_sebit_route_owner_scout:
	$(PYTHON) scripts/validate_tubitak_1711_sebit_route_owner_scout_20260618.py

tubitak_1711_acibadem_case_demand_side_scout:
	$(PYTHON) scripts/validate_tubitak_1711_acibadem_case_demand_side_scout_20260618.py

tuyze_education_route_owner_scout:
	$(PYTHON) scripts/validate_tuyze_education_route_owner_scout_20260618.py

tubitak_1711_three_gate_consortium_fit_map:
	$(PYTHON) scripts/validate_tubitak_1711_three_gate_consortium_fit_map_20260618.py

deu_digital_medicine_board_route_owner_scout:
	$(PYTHON) scripts/validate_deu_digital_medicine_board_route_owner_scout_20260618.py

ktu_ai_simulation_congress_route_owner_scout:
	$(PYTHON) scripts/validate_ktu_ai_simulation_congress_route_owner_scout_20260618.py

turkiye_health_ai_safety_route_owner_map:
	$(PYTHON) scripts/validate_turkiye_health_ai_safety_route_owner_map_20260618.py

turkiye_health_ai_safety_field_readiness_dashboard:
	$(PYTHON) scripts/validate_turkiye_health_ai_safety_field_readiness_dashboard_20260618.py

turkiye_clinician_ai_safety_mini_curriculum:
	$(PYTHON) scripts/validate_turkiye_clinician_ai_safety_mini_curriculum_20260618.py

turkiye_no_ranking_medical_ai_assurance_card:
	$(PYTHON) scripts/validate_turkiye_no_ranking_medical_ai_assurance_card_20260618.py

named_outreach_decision_matrix:
	$(PYTHON) scripts/generate_named_outreach_decision_matrix_20260618.py
	$(PYTHON) scripts/validate_named_outreach_decision_matrix_20260618.py

field_opportunity_decision_packages: tubitak_1711_ai_assurance_sidecar tubitak_1711_consortium_readiness_no_partner_gate named_outreach_decision_matrix

goktug_field_action_review_packet:
	$(PYTHON) scripts/generate_goktug_field_action_review_packet_20260618.py
	$(PYTHON) scripts/validate_goktug_field_action_review_packet_20260618.py

teknofest_public_share_clearance_packet:
	$(PYTHON) scripts/generate_teknofest_public_share_clearance_packet_20260618.py
	$(PYTHON) scripts/validate_teknofest_public_share_clearance_packet_20260618.py

tuyze_health_ai_safety_readiness_companion:
	$(PYTHON) scripts/validate_tuyze_health_ai_safety_readiness_companion_20260618.py

turkiye_health_ai_safety_outreach_roadmap:
	$(PYTHON) scripts/validate_turkiye_health_ai_safety_outreach_roadmap_20260618.py

hospital_medical_faculty_outreach_draft:
	$(PYTHON) scripts/validate_hospital_medical_faculty_outreach_draft_20260618.py

hacettepe_health_informatics_outreach_packet:
	$(PYTHON) scripts/validate_hacettepe_health_informatics_outreach_packet_20260618.py

hacettepe_health_management_ai_outreach_packet:
	$(PYTHON) scripts/validate_hacettepe_health_management_ai_outreach_packet_20260618.py

acibadem_medical_ethics_ai_outreach_packet:
	$(PYTHON) scripts/validate_acibadem_medical_ethics_ai_outreach_packet_20260618.py

current_medical_ai_intelligence_priority_update:
	$(PYTHON) scripts/generate_current_medical_ai_intelligence_priority_update_20260618_v0_1.py
	$(PYTHON) scripts/validate_current_medical_ai_intelligence_priority_update_20260618_v0_1.py

turkiye_ai_ethics_status_gate_note:
	$(PYTHON) scripts/generate_turkiye_ai_ethics_status_gate_note_v0_1.py
	$(PYTHON) scripts/validate_turkiye_ai_ethics_status_gate_note_v0_1.py

tr_clinical_ai_assurance_sandbox_readiness_gate:
	$(PYTHON) scripts/generate_tr_clinical_ai_assurance_sandbox_readiness_gate_checklist_v0_1.py
	$(PYTHON) scripts/validate_tr_clinical_ai_assurance_sandbox_readiness_gate_checklist_v0_1.py

sourcecheckup_medical_benchmark_boundary_delta:
	$(PYTHON) scripts/generate_sourcecheckup_medical_benchmark_boundary_delta_note_v0_1.py
	$(PYTHON) scripts/validate_sourcecheckup_medical_benchmark_boundary_delta_note_v0_1.py

paired_sandbox_boundary_delta: tr_clinical_ai_assurance_sandbox_readiness_gate sourcecheckup_medical_benchmark_boundary_delta

clinician_ai_literacy_sandbox_handoff_micro_module:
	$(PYTHON) scripts/generate_clinician_ai_literacy_sandbox_handoff_micro_module_v0_1.py
	$(PYTHON) scripts/validate_clinician_ai_literacy_sandbox_handoff_micro_module_v0_1.py

sourcecheckup_medical_source_support_delta_queue:
	$(PYTHON) scripts/generate_sourcecheckup_medical_source_support_delta_queue_v0_1.py
	$(PYTHON) scripts/validate_sourcecheckup_medical_source_support_delta_queue_v0_1.py

paired_literacy_source_support_delta: clinician_ai_literacy_sandbox_handoff_micro_module sourcecheckup_medical_source_support_delta_queue

sourcecheckup:
	$(PYTHON) scripts/sourcecheckup_medical.py self-test
	$(PYTHON) scripts/sourcecheckup_medical.py validate --input sourcecheckup/examples/sourcecheckup_seed_answers.jsonl --out-json sourcecheckup/build/sourcecheckup_seed_report.json --out-md sourcecheckup/build/sourcecheckup_seed_report.md

sourcecheckup_v02:
	$(PYTHON) scripts/sourcecheckup_medical.py validate --input sourcecheckup/examples/source_surface_examples_v0_2.jsonl --out-json sourcecheckup/build/source_surface_examples_v0_2_report.json --out-md sourcecheckup/build/source_surface_examples_v0_2_report.md

sourcecheckup_contrib_v02:
	$(PYTHON) scripts/validate_sourcecheckup_contribution_v0_2.py
	$(PYTHON) scripts/generate_red_flag_contributor_examples_v0_1.py
	$(PYTHON) scripts/validate_red_flag_contributor_examples_v0_1.py

sourcecheckup_public_issue:
	$(PYTHON) scripts/validate_sourcecheckup_public_contributor_issue_v0_1.py

sourcecheckup_repo_run_guide:
	$(PYTHON) scripts/sourcecheckup_repo_doctor_v0_1.py
	$(PYTHON) scripts/generate_sourcecheckup_repo_run_guide_v0_1.py
	$(PYTHON) scripts/validate_sourcecheckup_repo_run_guide_v0_1.py

healthbench_medhelm_mapping:
	$(PYTHON) scripts/generate_healthbench_medhelm_mapping_note_v0_1.py
	$(PYTHON) scripts/validate_healthbench_medhelm_mapping_note_v0_1.py

benchmark_reviewer_questions:
	$(PYTHON) scripts/generate_benchmark_style_reviewer_questions_v0_1.py
	$(PYTHON) scripts/validate_benchmark_style_reviewer_questions_v0_1.py

reviewer_question_issue_templates:
	$(PYTHON) scripts/validate_benchmark_reviewer_question_issue_templates_v0_1.py

reviewer_question_intake_examples:
	$(PYTHON) scripts/generate_reviewer_question_intake_examples_v0_1.py
	$(PYTHON) scripts/validate_reviewer_question_intake_examples_v0_1.py

reviewer_question_intake_triage:
	$(PYTHON) scripts/generate_reviewer_question_intake_triage_board_v0_1.py
	$(PYTHON) scripts/validate_reviewer_question_intake_triage_board_v0_1.py

reviewer_question_wording_log:
	$(PYTHON) scripts/generate_reviewer_question_public_wording_decision_log_v0_1.py
	$(PYTHON) scripts/validate_reviewer_question_public_wording_decision_log_v0_1.py

reviewer_question_release_gates:
	$(PYTHON) scripts/generate_reviewer_question_release_gate_checklist_v0_1.py
	$(PYTHON) scripts/validate_reviewer_question_release_gate_checklist_v0_1.py

reviewer_question_gate_outcomes:
	$(PYTHON) scripts/generate_reviewer_question_release_gate_outcome_dashboard_v0_1.py
	$(PYTHON) scripts/validate_reviewer_question_release_gate_outcome_dashboard_v0_1.py

reviewer_question_release_packet:
	$(PYTHON) scripts/generate_reviewer_question_public_release_packet_v0_1.py
	$(PYTHON) scripts/validate_reviewer_question_public_release_packet_v0_1.py

reviewer_question_changelog:
	$(PYTHON) scripts/generate_reviewer_question_public_changelog_v0_1.py
	$(PYTHON) scripts/validate_reviewer_question_public_changelog_v0_1.py

reviewer_question_release_index:
	$(PYTHON) scripts/generate_reviewer_question_public_release_index_v0_1.py
	$(PYTHON) scripts/validate_reviewer_question_public_release_index_v0_1.py

reviewer_question_contributor_digest:
	$(PYTHON) scripts/generate_reviewer_question_public_contributor_digest_v0_1.py
	$(PYTHON) scripts/validate_reviewer_question_public_contributor_digest_v0_1.py

reviewer_question_maintainer_handoff:
	$(PYTHON) scripts/generate_reviewer_question_maintainer_handoff_notes_v0_1.py
	$(PYTHON) scripts/validate_reviewer_question_maintainer_handoff_notes_v0_1.py

reviewer_question_maintainer_closeout_digest:
	$(PYTHON) scripts/generate_reviewer_question_maintainer_closeout_digest_v0_1.py
	$(PYTHON) scripts/validate_reviewer_question_maintainer_closeout_digest_v0_1.py

reviewer_question_maintainer_release_readiness_digest:
	$(PYTHON) scripts/generate_reviewer_question_maintainer_release_readiness_digest_v0_1.py
	$(PYTHON) scripts/validate_reviewer_question_maintainer_release_readiness_digest_v0_1.py

reviewer_question_maintainer_evidence_map:
	$(PYTHON) scripts/generate_reviewer_question_maintainer_evidence_map_v0_1.py
	$(PYTHON) scripts/validate_reviewer_question_maintainer_evidence_map_v0_1.py

reviewer_question_maintainer_audit_trail_packet:
	$(PYTHON) scripts/generate_reviewer_question_maintainer_audit_trail_packet_v0_1.py
	$(PYTHON) scripts/validate_reviewer_question_maintainer_audit_trail_packet_v0_1.py

reviewer_question_maintainer_release_candidate_summary:
	$(PYTHON) scripts/generate_reviewer_question_maintainer_release_candidate_summary_v0_1.py
	$(PYTHON) scripts/validate_reviewer_question_maintainer_release_candidate_summary_v0_1.py

reviewer_question_maintainer_public_preview_decision_log:
	$(PYTHON) scripts/generate_reviewer_question_maintainer_public_preview_decision_log_v0_1.py
	$(PYTHON) scripts/validate_reviewer_question_maintainer_public_preview_decision_log_v0_1.py

reviewer_question_maintainer_public_preview_handoff_summary:
	$(PYTHON) scripts/generate_reviewer_question_maintainer_public_preview_handoff_summary_v0_1.py
	$(PYTHON) scripts/validate_reviewer_question_maintainer_public_preview_handoff_summary_v0_1.py

reviewer_question_maintainer_public_preview_closure_checklist:
	$(PYTHON) scripts/generate_reviewer_question_maintainer_public_preview_closure_checklist_v0_1.py
	$(PYTHON) scripts/validate_reviewer_question_maintainer_public_preview_closure_checklist_v0_1.py

reviewer_question_maintainer_public_preview_archive_digest:
	$(PYTHON) scripts/generate_reviewer_question_maintainer_public_preview_archive_digest_v0_1.py
	$(PYTHON) scripts/validate_reviewer_question_maintainer_public_preview_archive_digest_v0_1.py

reviewer_question_maintainer_public_preview_index_rollup:
	$(PYTHON) scripts/generate_reviewer_question_maintainer_public_preview_index_rollup_v0_1.py
	$(PYTHON) scripts/validate_reviewer_question_maintainer_public_preview_index_rollup_v0_1.py

reviewer_question_maintainer_public_preview_repository_navigation_note:
	$(PYTHON) scripts/generate_reviewer_question_maintainer_public_preview_repository_navigation_note_v0_1.py
	$(PYTHON) scripts/validate_reviewer_question_maintainer_public_preview_repository_navigation_note_v0_1.py

reviewer_question_maintainer_public_preview_release_card:
	$(PYTHON) scripts/generate_reviewer_question_maintainer_public_preview_release_card_v0_1.py
	$(PYTHON) scripts/validate_reviewer_question_maintainer_public_preview_release_card_v0_1.py

reviewer_question_maintainer_public_preview_contributor_route_note:
	$(PYTHON) scripts/generate_reviewer_question_maintainer_public_preview_contributor_route_note_v0_1.py
	$(PYTHON) scripts/validate_reviewer_question_maintainer_public_preview_contributor_route_note_v0_1.py

reviewer_question_maintainer_public_preview_issue_template_route_note:
	$(PYTHON) scripts/generate_reviewer_question_maintainer_public_preview_issue_template_route_note_v0_1.py
	$(PYTHON) scripts/validate_reviewer_question_maintainer_public_preview_issue_template_route_note_v0_1.py

reviewer_question_maintainer_public_preview_maintainer_acceptance_checklist:
	$(PYTHON) scripts/generate_reviewer_question_maintainer_public_preview_maintainer_acceptance_checklist_v0_1.py
	$(PYTHON) scripts/validate_reviewer_question_maintainer_public_preview_maintainer_acceptance_checklist_v0_1.py

reviewer_question_maintainer_public_preview_acceptance_closeout_digest:
	$(PYTHON) scripts/generate_reviewer_question_maintainer_public_preview_acceptance_closeout_digest_v0_1.py
	$(PYTHON) scripts/validate_reviewer_question_maintainer_public_preview_acceptance_closeout_digest_v0_1.py

reviewer_question_maintainer_public_preview_acceptance_archive_index:
	$(PYTHON) scripts/generate_reviewer_question_maintainer_public_preview_acceptance_archive_index_v0_1.py
	$(PYTHON) scripts/validate_reviewer_question_maintainer_public_preview_acceptance_archive_index_v0_1.py

reviewer_question_maintainer_public_preview_acceptance_archive_release_note:
	$(PYTHON) scripts/generate_reviewer_question_maintainer_public_preview_acceptance_archive_release_note_v0_1.py
	$(PYTHON) scripts/validate_reviewer_question_maintainer_public_preview_acceptance_archive_release_note_v0_1.py

reviewer_question_maintainer_public_preview_acceptance_archive_closure_note:
	$(PYTHON) scripts/generate_reviewer_question_maintainer_public_preview_acceptance_archive_closure_note_v0_1.py
	$(PYTHON) scripts/validate_reviewer_question_maintainer_public_preview_acceptance_archive_closure_note_v0_1.py

reviewer_question_maintainer_public_preview_acceptance_archive_final_index:
	$(PYTHON) scripts/generate_reviewer_question_maintainer_public_preview_acceptance_archive_final_index_v0_1.py
	$(PYTHON) scripts/validate_reviewer_question_maintainer_public_preview_acceptance_archive_final_index_v0_1.py

reviewer_question_maintainer_public_preview_acceptance_archive_handoff_packet:
	$(PYTHON) scripts/generate_reviewer_question_maintainer_public_preview_acceptance_archive_handoff_packet_v0_1.py
	$(PYTHON) scripts/validate_reviewer_question_maintainer_public_preview_acceptance_archive_handoff_packet_v0_1.py

reviewer_question_maintainer_public_preview_acceptance_archive_steward_note:
	$(PYTHON) scripts/generate_reviewer_question_maintainer_public_preview_acceptance_archive_steward_note_v0_1.py
	$(PYTHON) scripts/validate_reviewer_question_maintainer_public_preview_acceptance_archive_steward_note_v0_1.py

reviewer_question_maintainer_public_preview_acceptance_archive_steward_index:
	$(PYTHON) scripts/generate_reviewer_question_maintainer_public_preview_acceptance_archive_steward_index_v0_1.py
	$(PYTHON) scripts/validate_reviewer_question_maintainer_public_preview_acceptance_archive_steward_index_v0_1.py

reviewer_question_maintainer_public_preview_acceptance_archive_stewardship_closeout:
	$(PYTHON) scripts/generate_reviewer_question_maintainer_public_preview_acceptance_archive_stewardship_closeout_v0_1.py
	$(PYTHON) scripts/validate_reviewer_question_maintainer_public_preview_acceptance_archive_stewardship_closeout_v0_1.py

reviewer_question_maintainer_public_preview_acceptance_archive_stewardship_digest:
	$(PYTHON) scripts/generate_reviewer_question_maintainer_public_preview_acceptance_archive_stewardship_digest_v0_1.py
	$(PYTHON) scripts/validate_reviewer_question_maintainer_public_preview_acceptance_archive_stewardship_digest_v0_1.py

reviewer_question_maintainer_public_preview_acceptance_archive_public_handoff_note:
	$(PYTHON) scripts/generate_reviewer_question_maintainer_public_preview_acceptance_archive_public_handoff_note_v0_1.py
	$(PYTHON) scripts/validate_reviewer_question_maintainer_public_preview_acceptance_archive_public_handoff_note_v0_1.py

reviewer_question_maintainer_public_preview_acceptance_archive_public_handoff_digest:
	$(PYTHON) scripts/generate_reviewer_question_maintainer_public_preview_acceptance_archive_public_handoff_digest_v0_1.py
	$(PYTHON) scripts/validate_reviewer_question_maintainer_public_preview_acceptance_archive_public_handoff_digest_v0_1.py

reviewer_question_maintainer_public_preview_acceptance_archive_public_handoff_release_index:
	$(PYTHON) scripts/generate_reviewer_question_maintainer_public_preview_acceptance_archive_public_handoff_release_index_v0_1.py
	$(PYTHON) scripts/validate_reviewer_question_maintainer_public_preview_acceptance_archive_public_handoff_release_index_v0_1.py

reviewer_question_maintainer_public_preview_acceptance_archive_public_handoff_release_note:
	$(PYTHON) scripts/generate_reviewer_question_maintainer_public_preview_acceptance_archive_public_handoff_release_note_v0_1.py
	$(PYTHON) scripts/validate_reviewer_question_maintainer_public_preview_acceptance_archive_public_handoff_release_note_v0_1.py

reviewer_question_maintainer_public_preview_acceptance_archive_public_handoff_closure_note:
	$(PYTHON) scripts/generate_reviewer_question_maintainer_public_preview_acceptance_archive_public_handoff_closure_note_v0_1.py
	$(PYTHON) scripts/validate_reviewer_question_maintainer_public_preview_acceptance_archive_public_handoff_closure_note_v0_1.py

label_audit_public_issue:
	$(PYTHON) scripts/validate_label_audit_public_contributor_issue_v0_1.py

label_audit_examples:
	$(PYTHON) scripts/generate_label_audit_example_intake_v0_1.py
	$(PYTHON) scripts/validate_label_audit_example_intake_v0_1.py

label_audit_dashboard:
	$(PYTHON) scripts/generate_label_audit_example_dashboard_v0_1.py
	$(PYTHON) scripts/validate_label_audit_example_dashboard_v0_1.py

label_audit_triage:
	$(PYTHON) scripts/generate_label_audit_maintainer_triage_board_v0_1.py
	$(PYTHON) scripts/validate_label_audit_maintainer_triage_board_v0_1.py

label_audit_wording_log:
	$(PYTHON) scripts/generate_label_audit_public_wording_decision_log_v0_1.py
	$(PYTHON) scripts/validate_label_audit_public_wording_decision_log_v0_1.py

label_audit_release_gates:
	$(PYTHON) scripts/generate_label_audit_release_gate_checklist_v0_1.py
	$(PYTHON) scripts/validate_label_audit_release_gate_checklist_v0_1.py

label_audit_outcome_dashboard:
	$(PYTHON) scripts/generate_label_audit_release_gate_outcome_dashboard_v0_1.py
	$(PYTHON) scripts/validate_label_audit_release_gate_outcome_dashboard_v0_1.py

label_audit_release_packet:
	$(PYTHON) scripts/generate_label_audit_release_note_packet_v0_1.py
	$(PYTHON) scripts/validate_label_audit_release_note_packet_v0_1.py

label_audit_changelog:
	$(PYTHON) scripts/generate_label_audit_public_changelog_v0_1.py
	$(PYTHON) scripts/validate_label_audit_public_changelog_v0_1.py

label_audit_release_index:
	$(PYTHON) scripts/generate_label_audit_public_release_index_v0_1.py
	$(PYTHON) scripts/validate_label_audit_public_release_index_v0_1.py

label_audit_contributor_digest:
	$(PYTHON) scripts/generate_label_audit_public_contributor_digest_v0_1.py
	$(PYTHON) scripts/validate_label_audit_public_contributor_digest_v0_1.py

label_audit_maintainer_handoff:
	$(PYTHON) scripts/generate_label_audit_maintainer_handoff_notes_v0_1.py
	$(PYTHON) scripts/validate_label_audit_maintainer_handoff_notes_v0_1.py

label_audit_maintainer_closeout_digest:
	$(PYTHON) scripts/generate_label_audit_maintainer_closeout_digest_v0_1.py
	$(PYTHON) scripts/validate_label_audit_maintainer_closeout_digest_v0_1.py

label_audit_maintainer_release_readiness_digest:
	$(PYTHON) scripts/generate_label_audit_maintainer_release_readiness_digest_v0_1.py
	$(PYTHON) scripts/validate_label_audit_maintainer_release_readiness_digest_v0_1.py

label_audit_maintainer_evidence_map:
	$(PYTHON) scripts/generate_label_audit_maintainer_evidence_map_v0_1.py
	$(PYTHON) scripts/validate_label_audit_maintainer_evidence_map_v0_1.py

label_audit_maintainer_audit_trail_packet:
	$(PYTHON) scripts/generate_label_audit_maintainer_audit_trail_packet_v0_1.py
	$(PYTHON) scripts/validate_label_audit_maintainer_audit_trail_packet_v0_1.py

label_audit_maintainer_release_candidate_summary:
	$(PYTHON) scripts/generate_label_audit_maintainer_release_candidate_summary_v0_1.py
	$(PYTHON) scripts/validate_label_audit_maintainer_release_candidate_summary_v0_1.py

label_audit_maintainer_public_preview_decision_log:
	$(PYTHON) scripts/generate_label_audit_maintainer_public_preview_decision_log_v0_1.py
	$(PYTHON) scripts/validate_label_audit_maintainer_public_preview_decision_log_v0_1.py

label_audit_maintainer_public_preview_handoff_summary:
	$(PYTHON) scripts/generate_label_audit_maintainer_public_preview_handoff_summary_v0_1.py
	$(PYTHON) scripts/validate_label_audit_maintainer_public_preview_handoff_summary_v0_1.py

label_audit_maintainer_public_preview_closure_checklist:
	$(PYTHON) scripts/generate_label_audit_maintainer_public_preview_closure_checklist_v0_1.py
	$(PYTHON) scripts/validate_label_audit_maintainer_public_preview_closure_checklist_v0_1.py

bilge_readiness_queue:
	$(PYTHON) scripts/generate_bilge_readiness_queue_v0_1.py
	$(PYTHON) scripts/validate_bilge_readiness_queue_v0_1.py

tubitak_1711_readiness_packet:
	$(PYTHON) scripts/generate_tubitak_1711_collaboration_readiness_packet_v0_1.py
	$(PYTHON) scripts/validate_tubitak_1711_collaboration_readiness_packet_v0_1.py

sourcecheckup_expansion_dashboard:
	$(PYTHON) scripts/sourcecheckup_medical.py validate --input sourcecheckup/examples/source_surface_examples_v0_2.jsonl --out-json sourcecheckup/build/source_surface_examples_v0_2_report.json --out-md sourcecheckup/build/source_surface_examples_v0_2_report.md
	$(PYTHON) scripts/validate_sourcecheckup_contribution_v0_2.py
	$(PYTHON) scripts/generate_red_flag_contributor_examples_v0_1.py
	$(PYTHON) scripts/validate_red_flag_contributor_examples_v0_1.py
	$(PYTHON) scripts/validate_source_claim_review_queue_v0_1.py
	$(PYTHON) scripts/generate_sourcecheckup_example_expansion_dashboard_v0_2.py
	$(PYTHON) scripts/validate_sourcecheckup_example_expansion_dashboard_v0_2.py

.PHONY: sourcecheckup_medical_source_claim_walkthrough
sourcecheckup_medical_source_claim_walkthrough:
	$(PYTHON) scripts/generate_sourcecheckup_medical_source_claim_walkthrough_v0_1.py
	$(PYTHON) scripts/validate_sourcecheckup_medical_source_claim_walkthrough_v0_1.py

sourcecheckup_tr_medllm_routing:
	$(PYTHON) scripts/generate_sourcecheckup_tr_medllm_assurance_routing_map_v0_1.py
	$(PYTHON) scripts/validate_sourcecheckup_tr_medllm_assurance_routing_map_v0_1.py

source_review_worksheets:
	$(PYTHON) scripts/generate_source_review_worksheets_v0_1.py
	$(PYTHON) scripts/validate_source_review_worksheets_v0_1.py

red_flag_warning_checklist:
	$(PYTHON) scripts/generate_red_flag_warning_checklist_v0_1.py
	$(PYTHON) scripts/validate_red_flag_warning_checklist_v0_1.py

red_flag_contributor_examples:
	$(PYTHON) scripts/validate_sourcecheckup_contribution_v0_2.py
	$(PYTHON) scripts/generate_red_flag_contributor_examples_v0_1.py
	$(PYTHON) scripts/validate_red_flag_contributor_examples_v0_1.py

sourcecheckup_turkish_institutional_wording:
	$(PYTHON) scripts/generate_sourcecheckup_turkish_institutional_wording_examples_v0_1.py
	$(PYTHON) scripts/validate_sourcecheckup_turkish_institutional_wording_examples_v0_1.py

warning_sign_role_table:
	$(PYTHON) scripts/generate_warning_sign_reviewer_role_table_v0_1.py
	$(PYTHON) scripts/validate_warning_sign_reviewer_role_table_v0_1.py

label_audit_role_table:
	$(PYTHON) scripts/generate_label_audit_reviewer_role_table_v0_1.py
	$(PYTHON) scripts/validate_label_audit_reviewer_role_table_v0_1.py

source_claim_queue:
	$(PYTHON) scripts/validate_source_claim_review_queue_v0_1.py

health_data_quality_card:
	$(PYTHON) scripts/validate_health_data_quality_card_v0_1.py

boundary_notes:
	$(PYTHON) scripts/validate_boundary_notes_v0_1.py

assurance_card_template:
	$(PYTHON) scripts/validate_assurance_card_template_v0_1.py

assurance_release_gate_map:
	$(PYTHON) scripts/generate_assurance_release_gate_example_map_v0_1.py
	$(PYTHON) scripts/validate_assurance_release_gate_example_map_v0_1.py

clinician_literacy_map:
	$(PYTHON) scripts/generate_clinician_literacy_release_gate_lesson_map_v0_1.py
	$(PYTHON) scripts/validate_clinician_literacy_release_gate_lesson_map_v0_1.py

leaderboard:
	$(PYTHON) scripts/validate_leaderboard_template_v0_1.py

leaderboard_report:
	$(PYTHON) scripts/validate_leaderboard_template_v0_1.py
	$(PYTHON) scripts/generate_leaderboard_report_v0_1.py

case_intake:
	$(PYTHON) scripts/validate_failure_atlas_case_intake_v0_1.py
	$(PYTHON) scripts/generate_failure_atlas_case_intake_report_v0_1.py

taxonomy_dashboard:
	$(PYTHON) scripts/validate_failure_atlas_case_intake_v0_1.py
	$(PYTHON) scripts/generate_failure_atlas_taxonomy_dashboard_v0_1.py

tr_medllm_pack:
	$(PYTHON) scripts/validate_failure_atlas_case_intake_v0_1.py --input tr_medllm_safetybench/synthetic_risk_pack_v0_1.jsonl
	$(PYTHON) scripts/validate_tr_medllm_specialty_spread_v0_1.py

tr_medllm_specialty_spread:
	$(PYTHON) scripts/validate_tr_medllm_specialty_spread_v0_1.py
	$(PYTHON) scripts/generate_tr_medllm_specialty_spread_dashboard_v0_1.py
	$(PYTHON) scripts/validate_tr_medllm_specialty_dashboard_v0_1.py

tr_medllm_specialty_dashboard:
	$(PYTHON) scripts/generate_tr_medllm_specialty_spread_dashboard_v0_1.py
	$(PYTHON) scripts/validate_tr_medllm_specialty_dashboard_v0_1.py

clinician_review_queue:
	$(PYTHON) scripts/validate_failure_atlas_case_intake_v0_1.py
	$(PYTHON) scripts/generate_clinician_review_queue_v0_1.py

clinician_review_protocol:
	$(PYTHON) scripts/validate_clinician_review_protocol_v0_1.py

release_note:
	$(PYTHON) scripts/validate_public_release_note_v0_1.py
