#!/usr/bin/env python3
from __future__ import annotations

import re
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
README = ROOT / "README.md"

SECTION_TITLE = "2026 06 25 public route and report hygiene surfaces"

REQUIRED_LINKS = {
    "docs/HEALTH_AI_ASSURANCE_OPPORTUNITY_RADAR_20260625.md",
    "docs/TEKNOFEST_HEALTH_AI_REPORT_CLAIM_HYGIENE_CHECKLIST_20260625.md",
    "docs/AI_ALLIANCE_MEDHELM_FOLLOW_UP_PREP_20260625.md",
    "docs/PUBLIC_GITHUB_ROUTE_WATCHLIST_20260625.md",
    "docs/PUBLIC_VISIBILITY_CLAIM_GATE_20260625.md",
    "docs/PUBLIC_REVIEW_OPERATING_SYSTEM_20260625.md",
    "docs/REPO_ACCELERATION_NORTH_STAR_20260625.md",
    "docs/CLINICIAN_SEVERITY_LAYER_SEED_ROWS_20260625.md",
    "docs/MEDICAL_AI_FIELD_COMMAND_PLAN_20260625.md",
    "docs/TURKISH_INTERNAL_MEDICINE_SAFETY_EVAL_V0_1_20260625.md",
    "docs/CLINICAL_INTELLIGENCE_STACK_MANIFESTO_20260625.md",
    "docs/CLINICAL_STATE_LANGUAGE_V0_1_20260625.md",
    "docs/CLINICAL_TRAJECTORY_ENGINE_V0_1_20260625.md",
    "docs/MEDICAL_REASONING_VERIFIER_V0_1_20260625.md",
    "docs/AGENTIC_MEDICINE_SANDBOX_V0_1_20260625.md",
    "docs/CLINICAL_INTELLIGENCE_STACK_GLOBAL_TARGET_MAP_20260625.md",
    "scripts/validate_clinical_state_language_v0_1.py",
    "data/clinical_trajectory_engine_transition_fixtures_v0_1_20260625.jsonl",
    "scripts/score_medical_reasoning_verifier_v0_1.py",
    "data/agentic_medicine_sandbox_event_fixtures_v0_1_20260625.jsonl",
    "docs/MEDICAL_INTELLIGENCE_ATLAS_V0_1_20260625.md",
    "docs/medical_intelligence_atlas_coverage_dashboard.md",
    "data/medical_intelligence_atlas_release_gate_v0_1_20260625.json",
    "docs/MULTILINGUAL_MEDICAL_INTELLIGENCE_SOURCE_CHECK_V0_1_20260625.md",
    "data/multilingual_medical_intelligence_paired_state_examples_v0_1_20260625.jsonl",
    "data/multilingual_medical_intelligence_source_check_index_v0_1_20260625.json",
    "scripts/validate_multilingual_medical_intelligence_paired_state_examples_v0_1_20260625.py",
    "docs/MULTILINGUAL_MEDICAL_INTELLIGENCE_PUBLIC_WORDING_BANK_V0_1_20260625.md",
    "data/multilingual_medical_intelligence_public_wording_index_v0_1_20260625.json",
    "scripts/validate_multilingual_medical_intelligence_public_wording_bank_v0_1_20260625.py",
    "data/multilingual_medical_intelligence_public_wording_drift_negative_controls_v0_1_20260625.jsonl",
    "docs/MULTILINGUAL_MEDICAL_INTELLIGENCE_PUBLIC_WORDING_DRIFT_SCORE_REPORT_V0_1_20260625.md",
    "data/multilingual_medical_intelligence_public_wording_drift_score_report_v0_1_20260625.json",
    "scripts/build_multilingual_medical_intelligence_public_wording_drift_score_report_v0_1_20260625.py",
    "scripts/validate_multilingual_medical_intelligence_public_wording_drift_score_report_v0_1_20260625.py",
    "data/multilingual_medical_intelligence_public_wording_rewrite_candidates_v0_1_20260625.jsonl",
    "docs/MULTILINGUAL_MEDICAL_INTELLIGENCE_REWRITE_CANDIDATE_SCORE_REPORT_V0_1_20260625.md",
    "data/multilingual_medical_intelligence_rewrite_candidate_score_report_v0_1_20260625.json",
    "scripts/score_multilingual_medical_intelligence_rewrite_candidates_v0_1_20260625.py",
    "scripts/validate_multilingual_medical_intelligence_rewrite_candidate_score_report_v0_1_20260625.py",
    "data/multilingual_medical_intelligence_rewrite_candidate_cross_language_ambiguity_controls_v0_1_20260625.jsonl",
    "docs/MULTILINGUAL_MEDICAL_INTELLIGENCE_CROSS_LANGUAGE_AMBIGUITY_REPORT_V0_1_20260625.md",
    "data/multilingual_medical_intelligence_cross_language_ambiguity_report_v0_1_20260625.json",
    "scripts/score_multilingual_medical_intelligence_cross_language_ambiguity_controls_v0_1_20260625.py",
    "scripts/validate_multilingual_medical_intelligence_cross_language_ambiguity_report_v0_1_20260625.py",
    "data/multilingual_medical_intelligence_rewrite_candidate_cross_language_negation_audience_controls_v0_1_20260625.jsonl",
    "docs/MULTILINGUAL_MEDICAL_INTELLIGENCE_CROSS_LANGUAGE_NEGATION_AUDIENCE_REPORT_V0_1_20260625.md",
    "data/multilingual_medical_intelligence_cross_language_negation_audience_report_v0_1_20260625.json",
    "scripts/score_multilingual_medical_intelligence_cross_language_negation_audience_controls_v0_1_20260625.py",
    "scripts/validate_multilingual_medical_intelligence_cross_language_negation_audience_report_v0_1_20260625.py",
    "data/multilingual_medical_intelligence_rewrite_candidate_cross_language_scope_anchor_controls_v0_1_20260625.jsonl",
    "docs/MULTILINGUAL_MEDICAL_INTELLIGENCE_CROSS_LANGUAGE_SCOPE_ANCHOR_REPORT_V0_1_20260625.md",
    "data/multilingual_medical_intelligence_cross_language_scope_anchor_report_v0_1_20260625.json",
    "scripts/score_multilingual_medical_intelligence_cross_language_scope_anchor_controls_v0_1_20260625.py",
    "scripts/validate_multilingual_medical_intelligence_cross_language_scope_anchor_report_v0_1_20260625.py",
    "data/multilingual_medical_intelligence_rewrite_candidate_cross_language_temporal_progression_controls_v0_1_20260625.jsonl",
    "docs/MULTILINGUAL_MEDICAL_INTELLIGENCE_CROSS_LANGUAGE_TEMPORAL_PROGRESSION_REPORT_V0_1_20260625.md",
    "data/multilingual_medical_intelligence_cross_language_temporal_progression_report_v0_1_20260625.json",
    "scripts/score_multilingual_medical_intelligence_cross_language_temporal_progression_controls_v0_1_20260625.py",
    "scripts/validate_multilingual_medical_intelligence_cross_language_temporal_progression_report_v0_1_20260625.py",
    "data/multilingual_medical_intelligence_rewrite_candidate_cross_language_uncertainty_calibration_controls_v0_1_20260625.jsonl",
    "docs/MULTILINGUAL_MEDICAL_INTELLIGENCE_CROSS_LANGUAGE_UNCERTAINTY_CALIBRATION_REPORT_V0_1_20260625.md",
    "data/multilingual_medical_intelligence_cross_language_uncertainty_calibration_report_v0_1_20260625.json",
    "scripts/score_multilingual_medical_intelligence_cross_language_uncertainty_calibration_controls_v0_1_20260625.py",
    "scripts/validate_multilingual_medical_intelligence_cross_language_uncertainty_calibration_report_v0_1_20260625.py",
    "data/multilingual_medical_intelligence_rewrite_candidate_cross_language_source_support_scope_reconciliation_controls_v0_1_20260625.jsonl",
    "docs/MULTILINGUAL_MEDICAL_INTELLIGENCE_CROSS_LANGUAGE_SOURCE_SUPPORT_SCOPE_RECONCILIATION_REPORT_V0_1_20260625.md",
    "data/multilingual_medical_intelligence_cross_language_source_support_scope_reconciliation_report_v0_1_20260625.json",
    "scripts/score_multilingual_medical_intelligence_cross_language_source_support_scope_reconciliation_controls_v0_1_20260625.py",
    "scripts/validate_multilingual_medical_intelligence_cross_language_source_support_scope_reconciliation_report_v0_1_20260625.py",
    "data/multilingual_medical_intelligence_rewrite_candidate_cross_language_source_recency_applicability_controls_v0_1_20260625.jsonl",
    "docs/MULTILINGUAL_MEDICAL_INTELLIGENCE_CROSS_LANGUAGE_SOURCE_RECENCY_APPLICABILITY_REPORT_V0_1_20260625.md",
    "data/multilingual_medical_intelligence_cross_language_source_recency_applicability_report_v0_1_20260625.json",
    "scripts/score_multilingual_medical_intelligence_cross_language_source_recency_applicability_controls_v0_1_20260625.py",
    "scripts/validate_multilingual_medical_intelligence_cross_language_source_recency_applicability_report_v0_1_20260625.py",
    "data/multilingual_medical_intelligence_rewrite_candidate_cross_language_source_conflict_provenance_controls_v0_1_20260625.jsonl",
    "docs/MULTILINGUAL_MEDICAL_INTELLIGENCE_CROSS_LANGUAGE_SOURCE_CONFLICT_PROVENANCE_REPORT_V0_1_20260625.md",
    "data/multilingual_medical_intelligence_cross_language_source_conflict_provenance_report_v0_1_20260625.json",
    "scripts/score_multilingual_medical_intelligence_cross_language_source_conflict_provenance_controls_v0_1_20260625.py",
    "scripts/validate_multilingual_medical_intelligence_cross_language_source_conflict_provenance_report_v0_1_20260625.py",
    "data/multilingual_medical_intelligence_rewrite_candidate_cross_language_reviewer_conflict_triage_controls_v0_1_20260625.jsonl",
    "docs/MULTILINGUAL_MEDICAL_INTELLIGENCE_CROSS_LANGUAGE_REVIEWER_CONFLICT_TRIAGE_REPORT_V0_1_20260625.md",
    "data/multilingual_medical_intelligence_cross_language_reviewer_conflict_triage_report_v0_1_20260625.json",
    "scripts/score_multilingual_medical_intelligence_cross_language_reviewer_conflict_triage_controls_v0_1_20260625.py",
    "scripts/validate_multilingual_medical_intelligence_cross_language_reviewer_conflict_triage_report_v0_1_20260625.py",
    "data/multilingual_medical_intelligence_rewrite_candidate_cross_language_reviewer_decision_rationale_controls_v0_1_20260625.jsonl",
    "docs/MULTILINGUAL_MEDICAL_INTELLIGENCE_CROSS_LANGUAGE_REVIEWER_DECISION_RATIONALE_REPORT_V0_1_20260625.md",
    "data/multilingual_medical_intelligence_cross_language_reviewer_decision_rationale_report_v0_1_20260625.json",
    "scripts/score_multilingual_medical_intelligence_cross_language_reviewer_decision_rationale_controls_v0_1_20260625.py",
    "scripts/validate_multilingual_medical_intelligence_cross_language_reviewer_decision_rationale_report_v0_1_20260625.py",
    "data/multilingual_medical_intelligence_rewrite_candidate_cross_language_reviewer_handoff_packet_controls_v0_1_20260625.jsonl",
    "docs/MULTILINGUAL_MEDICAL_INTELLIGENCE_CROSS_LANGUAGE_REVIEWER_HANDOFF_PACKET_REPORT_V0_1_20260625.md",
    "data/multilingual_medical_intelligence_cross_language_reviewer_handoff_packet_report_v0_1_20260625.json",
    "scripts/score_multilingual_medical_intelligence_cross_language_reviewer_handoff_packet_controls_v0_1_20260625.py",
    "scripts/validate_multilingual_medical_intelligence_cross_language_reviewer_handoff_packet_report_v0_1_20260625.py",
    "data/multilingual_medical_intelligence_rewrite_candidate_cross_language_reviewer_handoff_replay_controls_v0_1_20260625.jsonl",
    "docs/MULTILINGUAL_MEDICAL_INTELLIGENCE_CROSS_LANGUAGE_REVIEWER_HANDOFF_REPLAY_REPORT_V0_1_20260625.md",
    "data/multilingual_medical_intelligence_cross_language_reviewer_handoff_replay_report_v0_1_20260625.json",
    "scripts/score_multilingual_medical_intelligence_cross_language_reviewer_handoff_replay_controls_v0_1_20260625.py",
    "scripts/validate_multilingual_medical_intelligence_cross_language_reviewer_handoff_replay_report_v0_1_20260625.py",
    "data/multilingual_medical_intelligence_rewrite_candidate_cross_language_reviewer_replay_audit_trail_controls_v0_1_20260625.jsonl",
    "docs/MULTILINGUAL_MEDICAL_INTELLIGENCE_CROSS_LANGUAGE_REVIEWER_REPLAY_AUDIT_TRAIL_REPORT_V0_1_20260625.md",
    "data/multilingual_medical_intelligence_cross_language_reviewer_replay_audit_trail_report_v0_1_20260625.json",
    "scripts/score_multilingual_medical_intelligence_cross_language_reviewer_replay_audit_trail_controls_v0_1_20260625.py",
    "scripts/validate_multilingual_medical_intelligence_cross_language_reviewer_replay_audit_trail_report_v0_1_20260625.py",
    "data/multilingual_medical_intelligence_rewrite_candidate_cross_language_reviewer_replay_audit_trail_closeout_controls_v0_1_20260625.jsonl",
    "docs/MULTILINGUAL_MEDICAL_INTELLIGENCE_CROSS_LANGUAGE_REVIEWER_REPLAY_AUDIT_TRAIL_CLOSEOUT_REPORT_V0_1_20260625.md",
    "data/multilingual_medical_intelligence_cross_language_reviewer_replay_audit_trail_closeout_report_v0_1_20260625.json",
    "scripts/score_multilingual_medical_intelligence_cross_language_reviewer_replay_audit_trail_closeout_controls_v0_1_20260625.py",
    "scripts/validate_multilingual_medical_intelligence_cross_language_reviewer_replay_audit_trail_closeout_report_v0_1_20260625.py",
    "data/multilingual_medical_intelligence_rewrite_candidate_cross_language_reviewer_closeout_ledger_export_controls_v0_1_20260625.jsonl",
    "docs/MULTILINGUAL_MEDICAL_INTELLIGENCE_CROSS_LANGUAGE_REVIEWER_CLOSEOUT_LEDGER_EXPORT_REPORT_V0_1_20260625.md",
    "data/multilingual_medical_intelligence_cross_language_reviewer_closeout_ledger_export_report_v0_1_20260625.json",
    "scripts/score_multilingual_medical_intelligence_cross_language_reviewer_closeout_ledger_export_controls_v0_1_20260625.py",
    "scripts/validate_multilingual_medical_intelligence_cross_language_reviewer_closeout_ledger_export_report_v0_1_20260625.py",
    "data/multilingual_medical_intelligence_rewrite_candidate_cross_language_reviewer_closeout_ledger_reconciliation_controls_v0_1_20260625.jsonl",
    "docs/MULTILINGUAL_MEDICAL_INTELLIGENCE_CROSS_LANGUAGE_REVIEWER_CLOSEOUT_LEDGER_RECONCILIATION_REPORT_V0_1_20260625.md",
    "data/multilingual_medical_intelligence_cross_language_reviewer_closeout_ledger_reconciliation_report_v0_1_20260625.json",
    "scripts/score_multilingual_medical_intelligence_cross_language_reviewer_closeout_ledger_reconciliation_controls_v0_1_20260625.py",
    "scripts/validate_multilingual_medical_intelligence_cross_language_reviewer_closeout_ledger_reconciliation_report_v0_1_20260625.py",
    "data/multilingual_medical_intelligence_rewrite_candidate_cross_language_reviewer_closeout_ledger_reconciliation_exception_controls_v0_1_20260625.jsonl",
    "docs/MULTILINGUAL_MEDICAL_INTELLIGENCE_CROSS_LANGUAGE_REVIEWER_CLOSEOUT_LEDGER_RECONCILIATION_EXCEPTION_REPORT_V0_1_20260625.md",
    "data/multilingual_medical_intelligence_cross_language_reviewer_closeout_ledger_reconciliation_exception_report_v0_1_20260625.json",
    "scripts/score_multilingual_medical_intelligence_cross_language_reviewer_closeout_ledger_reconciliation_exception_controls_v0_1_20260625.py",
    "scripts/validate_multilingual_medical_intelligence_cross_language_reviewer_closeout_ledger_reconciliation_exception_report_v0_1_20260625.py",
    "data/multilingual_medical_intelligence_rewrite_candidate_cross_language_reviewer_closeout_ledger_reconciliation_exception_replay_controls_v0_1_20260625.jsonl",
    "docs/MULTILINGUAL_MEDICAL_INTELLIGENCE_CROSS_LANGUAGE_REVIEWER_CLOSEOUT_LEDGER_RECONCILIATION_EXCEPTION_REPLAY_REPORT_V0_1_20260625.md",
    "data/multilingual_medical_intelligence_cross_language_reviewer_closeout_ledger_reconciliation_exception_replay_report_v0_1_20260625.json",
    "scripts/score_multilingual_medical_intelligence_cross_language_reviewer_closeout_ledger_reconciliation_exception_replay_controls_v0_1_20260625.py",
    "scripts/validate_multilingual_medical_intelligence_cross_language_reviewer_closeout_ledger_reconciliation_exception_replay_report_v0_1_20260625.py",
    "data/multilingual_medical_intelligence_rewrite_candidate_cross_language_reviewer_closeout_ledger_reconciliation_exception_replay_closeout_controls_v0_1_20260625.jsonl",
    "docs/MULTILINGUAL_MEDICAL_INTELLIGENCE_CROSS_LANGUAGE_REVIEWER_CLOSEOUT_LEDGER_RECONCILIATION_EXCEPTION_REPLAY_CLOSEOUT_REPORT_V0_1_20260625.md",
    "data/multilingual_medical_intelligence_cross_language_reviewer_closeout_ledger_reconciliation_exception_replay_closeout_report_v0_1_20260625.json",
    "scripts/score_multilingual_medical_intelligence_cross_language_reviewer_closeout_ledger_reconciliation_exception_replay_closeout_controls_v0_1_20260625.py",
    "scripts/validate_multilingual_medical_intelligence_cross_language_reviewer_closeout_ledger_reconciliation_exception_replay_closeout_report_v0_1_20260625.py",
    "data/multilingual_medical_intelligence_rewrite_candidate_cross_language_reviewer_closeout_ledger_reconciliation_exception_replay_archive_controls_v0_1_20260625.jsonl",
    "docs/MULTILINGUAL_MEDICAL_INTELLIGENCE_CROSS_LANGUAGE_REVIEWER_CLOSEOUT_LEDGER_RECONCILIATION_EXCEPTION_REPLAY_ARCHIVE_REPORT_V0_1_20260625.md",
    "data/multilingual_medical_intelligence_cross_language_reviewer_closeout_ledger_reconciliation_exception_replay_archive_report_v0_1_20260625.json",
    "scripts/score_multilingual_medical_intelligence_cross_language_reviewer_closeout_ledger_reconciliation_exception_replay_archive_controls_v0_1_20260625.py",
    "scripts/validate_multilingual_medical_intelligence_cross_language_reviewer_closeout_ledger_reconciliation_exception_replay_archive_report_v0_1_20260625.py",
    "data/multilingual_medical_intelligence_rewrite_candidate_cross_language_reviewer_closeout_ledger_reconciliation_exception_replay_archive_rollup_controls_v0_1_20260625.jsonl",
    "docs/MULTILINGUAL_MEDICAL_INTELLIGENCE_CROSS_LANGUAGE_REVIEWER_CLOSEOUT_LEDGER_RECONCILIATION_EXCEPTION_REPLAY_ARCHIVE_ROLLUP_REPORT_V0_1_20260625.md",
    "data/multilingual_medical_intelligence_cross_language_reviewer_closeout_ledger_reconciliation_exception_replay_archive_rollup_report_v0_1_20260625.json",
    "scripts/score_multilingual_medical_intelligence_cross_language_reviewer_closeout_ledger_reconciliation_exception_replay_archive_rollup_controls_v0_1_20260625.py",
    "scripts/validate_multilingual_medical_intelligence_cross_language_reviewer_closeout_ledger_reconciliation_exception_replay_archive_rollup_report_v0_1_20260625.py",
    "data/multilingual_medical_intelligence_rewrite_candidate_cross_language_reviewer_closeout_ledger_reconciliation_exception_replay_archive_rollup_release_controls_v0_1_20260625.jsonl",
    "docs/MULTILINGUAL_MEDICAL_INTELLIGENCE_CROSS_LANGUAGE_REVIEWER_CLOSEOUT_LEDGER_RECONCILIATION_EXCEPTION_REPLAY_ARCHIVE_ROLLUP_RELEASE_REPORT_V0_1_20260625.md",
    "data/multilingual_medical_intelligence_cross_language_reviewer_closeout_ledger_reconciliation_exception_replay_archive_rollup_release_report_v0_1_20260625.json",
    "scripts/score_multilingual_medical_intelligence_cross_language_reviewer_closeout_ledger_reconciliation_exception_replay_archive_rollup_release_controls_v0_1_20260625.py",
    "scripts/validate_multilingual_medical_intelligence_cross_language_reviewer_closeout_ledger_reconciliation_exception_replay_archive_rollup_release_report_v0_1_20260625.py",
    "data/multilingual_medical_intelligence_rewrite_candidate_cross_language_reviewer_closeout_ledger_reconciliation_exception_replay_archive_rollup_release_handoff_controls_v0_1_20260625.jsonl",
    "docs/MULTILINGUAL_MEDICAL_INTELLIGENCE_CROSS_LANGUAGE_REVIEWER_CLOSEOUT_LEDGER_RECONCILIATION_EXCEPTION_REPLAY_ARCHIVE_ROLLUP_RELEASE_HANDOFF_REPORT_V0_1_20260625.md",
    "data/multilingual_medical_intelligence_cross_language_reviewer_closeout_ledger_reconciliation_exception_replay_archive_rollup_release_handoff_report_v0_1_20260625.json",
    "scripts/score_multilingual_medical_intelligence_cross_language_reviewer_closeout_ledger_reconciliation_exception_replay_archive_rollup_release_handoff_controls_v0_1_20260625.py",
    "scripts/validate_multilingual_medical_intelligence_cross_language_reviewer_closeout_ledger_reconciliation_exception_replay_archive_rollup_release_handoff_report_v0_1_20260625.py",
    "data/multilingual_medical_intelligence_rewrite_candidate_cross_language_reviewer_closeout_ledger_reconciliation_exception_replay_archive_rollup_release_handoff_closure_controls_v0_1_20260625.jsonl",
    "docs/MULTILINGUAL_MEDICAL_INTELLIGENCE_CROSS_LANGUAGE_REVIEWER_CLOSEOUT_LEDGER_RECONCILIATION_EXCEPTION_REPLAY_ARCHIVE_ROLLUP_RELEASE_HANDOFF_CLOSURE_REPORT_V0_1_20260625.md",
    "data/multilingual_medical_intelligence_cross_language_reviewer_closeout_ledger_reconciliation_exception_replay_archive_rollup_release_handoff_closure_report_v0_1_20260625.json",
    "scripts/score_multilingual_medical_intelligence_cross_language_reviewer_closeout_ledger_reconciliation_exception_replay_archive_rollup_release_handoff_closure_controls_v0_1_20260625.py",
    "scripts/validate_multilingual_medical_intelligence_cross_language_reviewer_closeout_ledger_reconciliation_exception_replay_archive_rollup_release_handoff_closure_report_v0_1_20260625.py",
    "data/multilingual_medical_intelligence_rewrite_candidate_cross_language_reviewer_closeout_ledger_reconciliation_exception_replay_archive_rollup_release_handoff_closure_archive_controls_v0_1_20260625.jsonl",
    "docs/MULTILINGUAL_MEDICAL_INTELLIGENCE_CROSS_LANGUAGE_REVIEWER_CLOSEOUT_LEDGER_RECONCILIATION_EXCEPTION_REPLAY_ARCHIVE_ROLLUP_RELEASE_HANDOFF_CLOSURE_ARCHIVE_REPORT_V0_1_20260625.md",
    "data/multilingual_medical_intelligence_cross_language_reviewer_closeout_ledger_reconciliation_exception_replay_archive_rollup_release_handoff_closure_archive_report_v0_1_20260625.json",
    "scripts/score_multilingual_medical_intelligence_cross_language_reviewer_closeout_ledger_reconciliation_exception_replay_archive_rollup_release_handoff_closure_archive_controls_v0_1_20260625.py",
    "scripts/validate_multilingual_medical_intelligence_cross_language_reviewer_closeout_ledger_reconciliation_exception_replay_archive_rollup_release_handoff_closure_archive_report_v0_1_20260625.py",
    "data/multilingual_medical_intelligence_rewrite_candidate_cross_language_reviewer_closeout_ledger_reconciliation_exception_replay_archive_rollup_release_handoff_closure_archive_reuse_controls_v0_1_20260625.jsonl",
    "data/multilingual_medical_intelligence_cross_language_reviewer_closeout_ledger_reconciliation_exception_replay_archive_rollup_release_handoff_closure_archive_reuse_report_v0_1_20260625.json",
    "docs/MULTILINGUAL_MEDICAL_INTELLIGENCE_CROSS_LANGUAGE_REVIEWER_CLOSEOUT_LEDGER_RECONCILIATION_EXCEPTION_REPLAY_ARCHIVE_ROLLUP_RELEASE_HANDOFF_CLOSURE_ARCHIVE_REUSE_REPORT_V0_1_20260625.md",
    "scripts/score_multilingual_medical_intelligence_cross_language_reviewer_closeout_ledger_reconciliation_exception_replay_archive_rollup_release_handoff_closure_archive_reuse_controls_v0_1_20260625.py",
    "scripts/validate_multilingual_medical_intelligence_cross_language_reviewer_closeout_ledger_reconciliation_exception_replay_archive_rollup_release_handoff_closure_archive_reuse_report_v0_1_20260625.py",
    "data/multilingual_medical_intelligence_rewrite_candidate_cross_language_reviewer_closeout_ledger_reconciliation_exception_replay_archive_rollup_release_handoff_closure_archive_reuse_release_controls_v0_1_20260625.jsonl",
    "data/multilingual_medical_intelligence_cross_language_reviewer_closeout_ledger_reconciliation_exception_replay_archive_rollup_release_handoff_closure_archive_reuse_release_report_v0_1_20260625.json",
    "docs/MULTILINGUAL_MEDICAL_INTELLIGENCE_CROSS_LANGUAGE_REVIEWER_CLOSEOUT_LEDGER_RECONCILIATION_EXCEPTION_REPLAY_ARCHIVE_ROLLUP_RELEASE_HANDOFF_CLOSURE_ARCHIVE_REUSE_RELEASE_REPORT_V0_1_20260625.md",
    "scripts/score_multilingual_medical_intelligence_cross_language_reviewer_closeout_ledger_reconciliation_exception_replay_archive_rollup_release_handoff_closure_archive_reuse_release_controls_v0_1_20260625.py",
    "scripts/validate_multilingual_medical_intelligence_cross_language_reviewer_closeout_ledger_reconciliation_exception_replay_archive_rollup_release_handoff_closure_archive_reuse_release_report_v0_1_20260625.py",
    "data/multilingual_medical_intelligence_rewrite_candidate_cross_language_reviewer_closeout_ledger_reconciliation_exception_replay_archive_rollup_release_handoff_closure_archive_reuse_release_handoff_controls_v0_1_20260625.jsonl",
    "data/multilingual_medical_intelligence_cross_language_reviewer_closeout_ledger_reconciliation_exception_replay_archive_rollup_release_handoff_closure_archive_reuse_release_handoff_report_v0_1_20260625.json",
    "docs/MULTILINGUAL_MEDICAL_INTELLIGENCE_CROSS_LANGUAGE_REVIEWER_CLOSEOUT_LEDGER_RECONCILIATION_EXCEPTION_REPLAY_ARCHIVE_ROLLUP_RELEASE_HANDOFF_CLOSURE_ARCHIVE_REUSE_RELEASE_HANDOFF_REPORT_V0_1_20260625.md",
    "scripts/score_multilingual_medical_intelligence_cross_language_reviewer_closeout_ledger_reconciliation_exception_replay_archive_rollup_release_handoff_closure_archive_reuse_release_handoff_controls_v0_1_20260625.py",
    "scripts/validate_multilingual_medical_intelligence_cross_language_reviewer_closeout_ledger_reconciliation_exception_replay_archive_rollup_release_handoff_closure_archive_reuse_release_handoff_report_v0_1_20260625.py",
    "data/multilingual_medical_intelligence_rewrite_candidate_cross_language_reviewer_closeout_ledger_reconciliation_exception_replay_archive_rollup_release_handoff_closure_archive_reuse_release_handoff_closure_controls_v0_1_20260625.jsonl",
    "data/multilingual_medical_intelligence_cross_language_reviewer_closeout_ledger_reconciliation_exception_replay_archive_rollup_release_handoff_closure_archive_reuse_release_handoff_closure_report_v0_1_20260625.json",
    "docs/MULTILINGUAL_MEDICAL_INTELLIGENCE_CROSS_LANGUAGE_REVIEWER_CLOSEOUT_LEDGER_RECONCILIATION_EXCEPTION_REPLAY_ARCHIVE_ROLLUP_RELEASE_HANDOFF_CLOSURE_ARCHIVE_REUSE_RELEASE_HANDOFF_CLOSURE_REPORT_V0_1_20260625.md",
    "scripts/score_multilingual_medical_intelligence_cross_language_reviewer_closeout_ledger_reconciliation_exception_replay_archive_rollup_release_handoff_closure_archive_reuse_release_handoff_closure_controls_v0_1_20260625.py",
    "scripts/validate_multilingual_medical_intelligence_cross_language_reviewer_closeout_ledger_reconciliation_exception_replay_archive_rollup_release_handoff_closure_archive_reuse_release_handoff_closure_report_v0_1_20260625.py",
    "data/multilingual_medical_intelligence_rewrite_candidate_cross_language_reviewer_closeout_ledger_reconciliation_exception_replay_archive_rollup_release_handoff_closure_archive_reuse_release_handoff_closure_archive_controls_v0_1_20260625.jsonl",
    "docs/MULTILINGUAL_MEDICAL_INTELLIGENCE_CROSS_LANGUAGE_REVIEWER_CLOSEOUT_LEDGER_RECONCILIATION_EXCEPTION_REPLAY_ARCHIVE_ROLLUP_RELEASE_HANDOFF_CLOSURE_ARCHIVE_REUSE_RELEASE_HANDOFF_CLOSURE_ARCHIVE_REPORT_V0_1_20260625.md",
    "data/multilingual_medical_intelligence_cross_language_reviewer_closeout_ledger_reconciliation_exception_replay_archive_rollup_release_handoff_closure_archive_reuse_release_handoff_closure_archive_report_v0_1_20260625.json",
    "scripts/score_multilingual_medical_intelligence_cross_language_reviewer_closeout_ledger_reconciliation_exception_replay_archive_rollup_release_handoff_closure_archive_reuse_release_handoff_closure_archive_controls_v0_1_20260625.py",
    "scripts/validate_multilingual_medical_intelligence_cross_language_reviewer_closeout_ledger_reconciliation_exception_replay_archive_rollup_release_handoff_closure_archive_reuse_release_handoff_closure_archive_report_v0_1_20260625.py",
    "data/multilingual_medical_intelligence_rewrite_candidate_cross_language_reviewer_closeout_ledger_reconciliation_exception_replay_archive_rollup_release_handoff_closure_archive_reuse_release_handoff_closure_archive_reuse_controls_v0_1_20260625.jsonl",
    "data/multilingual_medical_intelligence_cross_language_reviewer_closeout_ledger_reconciliation_exception_replay_archive_rollup_release_handoff_closure_archive_reuse_release_handoff_closure_archive_reuse_report_v0_1_20260625.json",
    "docs/MULTILINGUAL_MEDICAL_INTELLIGENCE_CROSS_LANGUAGE_REVIEWER_CLOSEOUT_LEDGER_RECONCILIATION_EXCEPTION_REPLAY_ARCHIVE_ROLLUP_RELEASE_HANDOFF_CLOSURE_ARCHIVE_REUSE_RELEASE_HANDOFF_CLOSURE_ARCHIVE_REUSE_REPORT_V0_1_20260625.md",
    "scripts/score_multilingual_medical_intelligence_cross_language_reviewer_closeout_ledger_reconciliation_exception_replay_archive_rollup_release_handoff_closure_archive_reuse_release_handoff_closure_archive_reuse_controls_v0_1_20260625.py",
    "scripts/validate_multilingual_medical_intelligence_cross_language_reviewer_closeout_ledger_reconciliation_exception_replay_archive_rollup_release_handoff_closure_archive_reuse_release_handoff_closure_archive_reuse_report_v0_1_20260625.py",
    "data/multilingual_medical_intelligence_rewrite_candidate_cross_language_reviewer_closeout_ledger_reconciliation_exception_replay_archive_rollup_release_handoff_closure_archive_reuse_release_handoff_closure_archive_reuse_release_controls_v0_1_20260625.jsonl",
    "docs/MULTILINGUAL_MEDICAL_INTELLIGENCE_CROSS_LANGUAGE_REVIEWER_CLOSEOUT_LEDGER_RECONCILIATION_EXCEPTION_REPLAY_ARCHIVE_ROLLUP_RELEASE_HANDOFF_CLOSURE_ARCHIVE_REUSE_RELEASE_HANDOFF_CLOSURE_ARCHIVE_REUSE_RELEASE_REPORT_V0_1_20260625.md",
    "data/multilingual_medical_intelligence_cross_language_reviewer_closeout_ledger_reconciliation_exception_replay_archive_rollup_release_handoff_closure_archive_reuse_release_handoff_closure_archive_reuse_release_report_v0_1_20260625.json",
    "scripts/score_multilingual_medical_intelligence_cross_language_reviewer_closeout_ledger_reconciliation_exception_replay_archive_rollup_release_handoff_closure_archive_reuse_release_handoff_closure_archive_reuse_release_controls_v0_1_20260625.py",
    "scripts/validate_multilingual_medical_intelligence_cross_language_reviewer_closeout_ledger_reconciliation_exception_replay_archive_rollup_release_handoff_closure_archive_reuse_release_handoff_closure_archive_reuse_release_report_v0_1_20260625.py",
    "data/multilingual_medical_intelligence_cross_language_reviewer_closeout_ledger_reconciliation_exception_replay_archive_rollup_release_handoff_closure_archive_reuse_release_handoff_closure_archive_reuse_release_handoff_controls_v0_1_20260625.jsonl",
    "data/multilingual_medical_intelligence_cross_language_reviewer_closeout_ledger_reconciliation_exception_replay_archive_rollup_release_handoff_closure_archive_reuse_release_handoff_closure_archive_reuse_release_handoff_report_v0_1_20260625.json",
    "docs/MULTILINGUAL_MEDICAL_INTELLIGENCE_CROSS_LANGUAGE_REVIEWER_CLOSEOUT_LEDGER_RECONCILIATION_EXCEPTION_REPLAY_ARCHIVE_ROLLUP_RELEASE_HANDOFF_CLOSURE_ARCHIVE_REUSE_RELEASE_HANDOFF_CLOSURE_ARCHIVE_REUSE_RELEASE_HANDOFF_REPORT_V0_1_20260625.md",
    "scripts/score_multilingual_medical_intelligence_cross_language_reviewer_closeout_ledger_reconciliation_exception_replay_archive_rollup_release_handoff_closure_archive_reuse_release_handoff_closure_archive_reuse_release_handoff_controls_v0_1_20260625.py",
    "scripts/validate_multilingual_medical_intelligence_cross_language_reviewer_closeout_ledger_reconciliation_exception_replay_archive_rollup_release_handoff_closure_archive_reuse_release_handoff_closure_archive_reuse_release_handoff_report_v0_1_20260625.py",
    "data/mmi_035_closure_controls_v0_1_20260625.jsonl",
    "data/mmi_035_closure_report_v0_1_20260625.json",
    "docs/MMI_035_CLOSURE_REPORT_V0_1_20260625.md",
    "scripts/score_mmi_035_closure_controls_v0_1_20260625.py",
    "scripts/validate_mmi_035_closure_report_v0_1_20260625.py",
    "data/mmi_036_closure_archive_controls_v0_1_20260625.jsonl",
    "data/mmi_036_closure_archive_report_v0_1_20260625.json",
    "docs/MMI_036_CLOSURE_ARCHIVE_REPORT_V0_1_20260625.md",
    "scripts/score_mmi_036_closure_archive_controls_v0_1_20260625.py",
    "scripts/validate_mmi_036_closure_archive_report_v0_1_20260625.py",
    "data/mmi_037_closure_archive_reuse_controls_v0_1_20260625.jsonl",
    "data/mmi_037_closure_archive_reuse_report_v0_1_20260625.json",
    "docs/MMI_037_CLOSURE_ARCHIVE_REUSE_REPORT_V0_1_20260625.md",
    "scripts/score_mmi_037_closure_archive_reuse_controls_v0_1_20260625.py",
    "scripts/validate_mmi_037_closure_archive_reuse_report_v0_1_20260625.py",
    "data/mmi_038_closure_archive_reuse_release_controls_v0_1_20260625.jsonl",
    "data/mmi_038_closure_archive_reuse_release_report_v0_1_20260625.json",
    "docs/MMI_038_CLOSURE_ARCHIVE_REUSE_RELEASE_REPORT_V0_1_20260625.md",
    "scripts/score_mmi_038_closure_archive_reuse_release_controls_v0_1_20260625.py",
    "scripts/validate_mmi_038_closure_archive_reuse_release_report_v0_1_20260625.py",
}

REQUIRED_PHRASES = [
    "natural authority or clearance overclaim blocking",
    "reviewer closeout ledger reconciliation exception replay archive rollup release handoff closure archive reuse release report",
    "reviewer closeout ledger reconciliation exception replay archive rollup release handoff closure archive reuse release signal counts",
    "cross language reviewer closeout ledger reconciliation exception replay archive rollup release handoff closure archive reuse release controls",
    "make multilingual_medical_intelligence_cross_language_reviewer_closeout_ledger_reconciliation_exception_replay_archive_rollup_release_handoff_closure_archive_reuse_release_controls",
    "Multilingual Medical Intelligence cross language reviewer closeout ledger reconciliation exception replay archive rollup release handoff closure archive reuse release controls",
    "reviewer closeout ledger reconciliation exception replay archive rollup release handoff closure archive reuse release handoff report",
    "reviewer closeout ledger reconciliation exception replay archive rollup release handoff closure archive reuse release handoff signal counts",
    "cross language reviewer closeout ledger reconciliation exception replay archive rollup release handoff closure archive reuse release handoff controls",
    "make multilingual_medical_intelligence_cross_language_reviewer_closeout_ledger_reconciliation_exception_replay_archive_rollup_release_handoff_closure_archive_reuse_release_handoff_controls",
    "Multilingual Medical Intelligence cross language reviewer closeout ledger reconciliation exception replay archive rollup release handoff closure archive reuse release handoff controls",
    "reviewer closeout ledger reconciliation exception replay archive rollup release handoff closure archive reuse release handoff closure report",
    "reviewer closeout ledger reconciliation exception replay archive rollup release handoff closure archive reuse release handoff closure signal counts",
    "cross language reviewer closeout ledger reconciliation exception replay archive rollup release handoff closure archive reuse release handoff closure controls",
    "make multilingual_medical_intelligence_cross_language_reviewer_closeout_ledger_reconciliation_exception_replay_archive_rollup_release_handoff_closure_archive_reuse_release_handoff_closure_controls",
    "Multilingual Medical Intelligence cross language reviewer closeout ledger reconciliation exception replay archive rollup release handoff closure archive reuse release handoff closure controls",
    "broad clinical validation deployment ranking partner institution regulatory publication authority or clearance overclaim blocking",
    "reviewer closeout ledger reconciliation exception replay archive rollup release handoff closure archive reuse release handoff closure archive reuse release report",
    "reviewer closeout ledger reconciliation exception replay archive rollup release handoff closure archive reuse release handoff closure archive reuse release signal counts",
    "cross language reviewer closeout ledger reconciliation exception replay archive rollup release handoff closure archive reuse release handoff closure archive reuse release controls",
    "make multilingual_medical_intelligence_cross_language_reviewer_closeout_ledger_reconciliation_exception_replay_archive_rollup_release_handoff_closure_archive_reuse_release_handoff_closure_archive_reuse_release_controls",
    "Multilingual Medical Intelligence cross language reviewer closeout ledger reconciliation exception replay archive rollup release handoff closure archive reuse release handoff closure archive reuse release controls",
    "reviewer closeout ledger reconciliation exception replay archive rollup release handoff closure archive reuse release handoff closure archive reuse release handoff report",
    "reviewer closeout ledger reconciliation exception replay archive rollup release handoff closure archive reuse release handoff closure archive reuse release handoff signal counts",
    "cross language reviewer closeout ledger reconciliation exception replay archive rollup release handoff closure archive reuse release handoff closure archive reuse release handoff controls",
    "make multilingual_medical_intelligence_cross_language_reviewer_closeout_ledger_reconciliation_exception_replay_archive_rollup_release_handoff_closure_archive_reuse_release_handoff_closure_archive_reuse_release_handoff_controls",
    "Multilingual Medical Intelligence cross language reviewer closeout ledger reconciliation exception replay archive rollup release handoff closure archive reuse release handoff closure archive reuse release handoff controls",
    "maps forty eight atlas nodes",
    "Current public navigation for the latest medical AI intelligence work",
    "without application, partner, device, clinical validation, or compliance claims",
    "ten gate checklist for safer project report language",
    "keeps acknowledgement separate from endorsement",
    "The AI Alliance issue 50",
    "lighteval pull request 1272",
    "inspect ai pull request 4343",
    "Before using any route state in public text",
    "make public_github_route_preflight",
    "live GitHub route state",
    "public post, comment, outreach, and reply text gate",
    "from turning into endorsement, acceptance, validation, or deployment claims",
    "generated public review flow",
    "one artifact per loop",
    "generated repo direction system",
    "clinician severity layer",
    "source support layer",
    "claim hygiene layer",
    "Turkish clinical context layer",
    "open source eval bridge",
    "72 hour queue",
    "ten generated seed rows",
    "clinical severity",
    "missing variable",
    "source support gap",
    "safe rewrite",
    "reviewer state",
    "Medical AI Field Command Plan",
    "source checked field plan",
    "FDA, WHO, IMDRF, HealthBench, MedGemma, MedHELM, AgentClinic",
    "TÜYZE, KDS, NeyimVar, TÜBİTAK, and TEKNOFEST",
    "internal medicine safety evaluation lane",
    "Turkish Internal Medicine Safety Eval v0.1",
    "generated 30 row synthetic Turkish internal medicine safety eval path",
    "v0.3 synthetic case set",
    "escalation, medication safety, laboratory interpretation, source support, and safe Turkish wording gates",
    "make internal_medicine_ai_safety_strategy",
    "Clinical Intelligence Stack Manifesto",
    "medical AI needs a clinical intelligence stack",
    "source anchors, stack layers, boundaries, and the first build command",
    "Clinical State Language v0.1",
    "patient state, timeline, missing data, hypotheses, evidence, action boundary",
    "Clinical Trajectory Engine v0.1",
    "twenty synthetic trajectory seed rows across clinical domains",
    "Medical Reasoning Verifier v0.1",
    "state completeness, timeline tracking, missing variable discipline",
    "Agentic Medicine Sandbox v0.1",
    "patient, clinician, test, source support, consultant, and follow up agents",
    "make clinical_intelligence_stack",
    "Clinical Intelligence Stack Global Target Map",
    "source anchored distribution map for reasoning model teams",
    "health benchmark builders, health foundation model developers",
    "Türkiye health AI decision ecosystem, and national technology circles",
    "make clinical_intelligence_stack_global_target_map",
    "Clinical State Language validator",
    "dependency free validator and normalizer",
    "canonical fixture output",
    "Clinical Trajectory Engine transition fixtures",
    "five synthetic trajectories with fifteen states and ten explicit transitions",
    "red flag, and action boundary checks",
    "Medical Reasoning Verifier scorer",
    "deterministic scorer for seven synthetic examples",
    "state completeness, timeline tracking, missing variable discipline",
    "uncertainty handling, action sequencing, source support, and forbidden claim avoidance",
    "Agentic Medicine Sandbox event fixtures",
    "three synthetic event flow scenarios",
    "patient simulator, clinician reasoner, test result emitter, source support checker, consultant simulator, and follow up monitor agents",
    "Medical Intelligence Atlas v0.1",
    "machine readable repo construction map",
    "build nodes, validators, risk gates, release states, and exact next builds",
    "Medical Intelligence Atlas Coverage Dashboard",
    "maps forty eight atlas nodes to local runtime artifacts",
    "validators, coverage focus, and open gap state",
    "Medical Intelligence Atlas Release Gate",
    "release gate for six Clinical Intelligence Stack layers",
    "synthetic boundary flags, source check state, and exact next action",
    "Multilingual Medical Intelligence Source Check",
    "paired Turkish English synthetic state check",
    "language ambiguity, missing data preservation, action boundary preservation",
    "source support preservation",
    "Multilingual Medical Intelligence paired state examples",
    "six paired Turkish English synthetic state rows",
    "emergency, medication safety, chronic disease, pregnancy, laboratory interpretation, and follow up contexts",
    "Multilingual Medical Intelligence source check index",
    "repo local synthetic pair evidence, boundary flags, ready status, and exact next action",
    "Multilingual Medical Intelligence paired state validator",
    "six pairs, twelve states, boundary flags, cross language checks",
    "private identifier absence, and forbidden claim absence",
    "Multilingual Medical Intelligence Public Wording Bank",
    "eight synthetic Turkish English public wording rows",
    "plain clinical language, missing data, source support, and action boundaries",
    "without diagnosis or treatment instruction",
    "Multilingual Medical Intelligence public wording index",
    "source pair coverage, boundary flags, validation command, ready status, and next build",
    "Multilingual Medical Intelligence public wording validator",
    "all six paired source state examples",
    "ASCII Turkish wording, private identifier absence, URL absence, forbidden claim absence, and patient facing instruction absence",
    "Multilingual Medical Intelligence public wording drift negative controls",
    "eight expected fail rewrite controls",
    "missing data removal, source support weakening, certainty increase, patient facing instruction, and diagnosis or treatment instruction drift",
    "Multilingual Medical Intelligence public wording drift score report",
    "local fixture triage report",
    "eight passing public wording rows",
    "eight expected fail drift controls",
    "drift signal counts",
    "failure reason counts",
    "reviewer triage",
    "without score certification",
    "Multilingual Medical Intelligence public wording drift score data",
    "source row coverage, source pair coverage, and release boundary flags",
    "Multilingual Medical Intelligence public wording drift score builder",
    "deterministic builder and freshness checker",
    "Multilingual Medical Intelligence public wording drift score validator",
    "JSON and Markdown drift triage report freshness",
    "Multilingual Medical Intelligence rewrite candidate fixture",
    "sixteen synthetic rewrite candidates",
    "source negative controls",
    "expected pass rows",
    "expected fail rows",
    "Multilingual Medical Intelligence rewrite candidate score report",
    "candidate public rewrites",
    "patient facing instruction",
    "diagnosis or treatment instruction drift",
    "Multilingual Medical Intelligence rewrite candidate score data",
    "sixteen candidate rows",
    "eight pass candidates",
    "eight blocked candidates",
    "blocked candidate counts",
    "Multilingual Medical Intelligence rewrite candidate scorer",
    "deterministic scorer and freshness checker",
    "Multilingual Medical Intelligence rewrite candidate score validator",
    "candidate fixture shape",
    "Multilingual Medical Intelligence cross language ambiguity controls",
    "twelve synthetic Turkish English ambiguity controls",
    "added certainty, source support shift, missing data softening, action boundary shift, and translation review removal",
    "Multilingual Medical Intelligence cross language ambiguity report",
    "six pass controls, six blocked controls",
    "translation clearance absence",
    "Multilingual Medical Intelligence cross language ambiguity data",
    "six signal types",
    "Multilingual Medical Intelligence cross language ambiguity scorer",
    "English and Turkish ASCII ambiguity drift",
    "Multilingual Medical Intelligence cross language ambiguity validator",
    "make multilingual_medical_intelligence_cross_language_ambiguity_controls",
    "six ambiguity signal types",
    "Multilingual Medical Intelligence cross language negation audience controls",
    "twelve synthetic Turkish English controls for negation inversion, warning softening, patient audience shift, clinician audience shift, and model audience shift",
    "Multilingual Medical Intelligence cross language negation audience report",
    "audience role clearance absence",
    "Multilingual Medical Intelligence cross language negation audience data",
    "negation and audience role output",
    "Multilingual Medical Intelligence cross language negation audience scorer",
    "negation inversion and audience role drift",
    "Multilingual Medical Intelligence cross language negation audience validator",
    "make multilingual_medical_intelligence_cross_language_negation_audience_controls",
    "six negation and audience role signal types",
    "Multilingual Medical Intelligence cross language scope anchor controls",
    "twelve synthetic Turkish English controls for missing variable anchors, actor role anchors, action boundary anchors, and local context anchors",
    "Multilingual Medical Intelligence cross language scope anchor report",
    "scope anchor clearance absence",
    "Multilingual Medical Intelligence cross language scope anchor data",
    "source row coverage",
    "Multilingual Medical Intelligence cross language scope anchor scorer",
    "missing variable erasure, actor role change, action boundary drift, and local context detachment",
    "Multilingual Medical Intelligence cross language scope anchor validator",
    "make multilingual_medical_intelligence_cross_language_scope_anchor_controls",
    "six scope anchor signal types",
    "Multilingual Medical Intelligence cross language temporal progression controls",
    "twelve synthetic Turkish English controls for duration shift, sequence reversal, follow up timing removal, interval precision loss, and care instruction creation drift",
    "Multilingual Medical Intelligence cross language temporal progression report",
    "temporal progression clearance absence",
    "Multilingual Medical Intelligence cross language temporal progression data",
    "temporal progression output",
    "Multilingual Medical Intelligence cross language temporal progression scorer",
    "duration drift, sequence drift, follow up timing drift, interval precision drift, and care instruction creation drift",
    "Multilingual Medical Intelligence cross language temporal progression validator",
    "make multilingual_medical_intelligence_cross_language_temporal_progression_controls",
    "six temporal progression signal types",
    "Multilingual Medical Intelligence cross language uncertainty calibration controls",
    "twelve synthetic Turkish English controls for confidence inflation, uncertainty marker removal, evidence gap closure, reviewer state downgrade, and confidence score creation drift",
    "Multilingual Medical Intelligence cross language uncertainty calibration report",
    "uncertainty calibration clearance absence",
    "Multilingual Medical Intelligence cross language uncertainty calibration data",
    "uncertainty calibration output",
    "Multilingual Medical Intelligence cross language uncertainty calibration scorer",
    "confidence inflation, uncertainty marker loss, evidence gap closure, reviewer state downgrade, and invented confidence score drift",
    "Multilingual Medical Intelligence cross language uncertainty calibration validator",
    "make multilingual_medical_intelligence_cross_language_uncertainty_calibration_controls",
    "six uncertainty calibration signal types",
    "Multilingual Medical Intelligence cross language source support scope reconciliation controls",
    "claim source support maps",
    "source support needs",
    "source limits",
    "reviewer hold",
    "Multilingual Medical Intelligence cross language source support scope reconciliation report",
    "source truth certification absence",
    "Multilingual Medical Intelligence cross language source support scope reconciliation data",
    "source support scope reconciliation output",
    "Multilingual Medical Intelligence cross language source support scope reconciliation scorer",
    "unsupported source authority creation",
    "cross language source scope detachment",
    "Multilingual Medical Intelligence cross language source support scope reconciliation validator",
    "claim source map shape",
    "make multilingual_medical_intelligence_cross_language_source_support_scope_reconciliation_controls",
    "six source support scope reconciliation signal types",
    "Multilingual Medical Intelligence cross language source recency applicability controls",
    "source date, recency status, population, setting, and applicability limits",
    "Multilingual Medical Intelligence cross language source recency applicability report",
    "source recency applicability clearance absence",
    "Multilingual Medical Intelligence cross language source recency applicability data",
    "source recency applicability output",
    "Multilingual Medical Intelligence cross language source recency applicability scorer",
    "source recency status inflation",
    "applicability limit removal",
    "Multilingual Medical Intelligence cross language source recency applicability validator",
    "source recency applicability map shape",
    "make multilingual_medical_intelligence_cross_language_source_recency_applicability_controls",
    "Multilingual Medical Intelligence cross language source conflict provenance controls",
    "source conflict erasure, source version drift, provenance chain break, attribution detachment, and unsupported conflict resolution",
    "make multilingual_medical_intelligence_cross_language_source_conflict_provenance_controls",
    "six source conflict provenance signal types",
    "source conflict provenance signal counts",
    "Multilingual Medical Intelligence cross language reviewer conflict triage controls",
    "reviewer hold, compare, reject, unresolved conflict, and triage label states",
    "Multilingual Medical Intelligence cross language reviewer conflict triage report",
    "reviewer hold compare reject routing",
    "Multilingual Medical Intelligence cross language reviewer conflict triage data",
    "triage state counts",
    "Multilingual Medical Intelligence cross language reviewer conflict triage scorer",
    "reviewer hold removal, compare route collapse, reject route softening, unresolved conflict clearing, and triage state mislabeling",
    "Multilingual Medical Intelligence cross language reviewer conflict triage validator",
    "make multilingual_medical_intelligence_cross_language_reviewer_conflict_triage_controls",
    "six reviewer conflict triage signal types",
    "Multilingual Medical Intelligence cross language reviewer decision rationale controls",
    "reviewer decision rationale, reviewer owner, unresolved state, decision boundary, and authority claim absence",
    "Multilingual Medical Intelligence cross language reviewer decision rationale report",
    "reviewer decision rationale signal types",
    "Multilingual Medical Intelligence cross language reviewer decision rationale data",
    "decision route counts",
    "Multilingual Medical Intelligence cross language reviewer decision rationale scorer",
    "rationale removal, reviewer owner drift, unresolved state erasure, decision boundary broadening, and authority claim creation",
    "Multilingual Medical Intelligence cross language reviewer decision rationale validator",
    "Multilingual Medical Intelligence cross language reviewer handoff packet controls",
    "reviewer handoff packet signal types",
    "evidence summary removal",
    "make multilingual_medical_intelligence_cross_language_reviewer_handoff_packet_controls",
    "Multilingual Medical Intelligence cross language reviewer handoff replay controls",
    "reviewer handoff replay signal types",
    "recheck trace removal",
    "appeal context removal",
    "route owner handoff",
    "make multilingual_medical_intelligence_cross_language_reviewer_handoff_replay_controls",
    "Multilingual Medical Intelligence cross language reviewer replay audit trail controls",
    "reviewer replay audit trail signal types",
    "comparison result removal",
    "owner signoff state removal",
    "unresolved branch removal",
    "make multilingual_medical_intelligence_cross_language_reviewer_replay_audit_trail_controls",
    "Multilingual Medical Intelligence cross language reviewer replay audit trail closeout controls",
    "reviewer replay audit trail closeout signal types",
    "closeout decision removal",
    "dissent note removal",
    "owner final state removal",
    "unresolved branch closure boundary removal",
    "closure comparison result removal",
    "make multilingual_medical_intelligence_cross_language_reviewer_replay_audit_trail_closeout_controls",
    "Multilingual Medical Intelligence cross language reviewer closeout ledger export controls",
    "Multilingual Medical Intelligence cross language reviewer closeout ledger export report",
    "Multilingual Medical Intelligence cross language reviewer closeout ledger export data",
    "Multilingual Medical Intelligence cross language reviewer closeout ledger export scorer",
    "Multilingual Medical Intelligence cross language reviewer closeout ledger export validator",
    "closeout decision export removal",
    "dissent note export removal",
    "owner final state export removal",
    "closure comparison result export removal",
    "unresolved branch closure boundary export removal",
    "authority or clearance claim creation",
    "make multilingual_medical_intelligence_cross_language_reviewer_closeout_ledger_export_controls",
    "reviewer closeout ledger export report",
    "Multilingual Medical Intelligence cross language reviewer closeout ledger reconciliation controls",
    "Multilingual Medical Intelligence cross language reviewer closeout ledger reconciliation report",
    "Multilingual Medical Intelligence cross language reviewer closeout ledger reconciliation data",
    "Multilingual Medical Intelligence cross language reviewer closeout ledger reconciliation scorer",
    "Multilingual Medical Intelligence cross language reviewer closeout ledger reconciliation validator",
    "closeout decision reconciliation mismatch",
    "dissent note reconciliation mismatch",
    "owner final state reconciliation mismatch",
    "unresolved branch closure boundary reconciliation mismatch",
    "closure comparison result reconciliation mismatch",
    "make multilingual_medical_intelligence_cross_language_reviewer_closeout_ledger_reconciliation_controls",
    "reviewer closeout ledger reconciliation report",
    "Multilingual Medical Intelligence cross language reviewer closeout ledger reconciliation exception controls",
    "Multilingual Medical Intelligence cross language reviewer closeout ledger reconciliation exception report",
    "Multilingual Medical Intelligence cross language reviewer closeout ledger reconciliation exception data",
    "Multilingual Medical Intelligence cross language reviewer closeout ledger reconciliation exception scorer",
    "Multilingual Medical Intelligence cross language reviewer closeout ledger reconciliation exception validator",
    "source closeout id exception detached",
    "exported ledger row id exception detached",
    "owner final state exception detached",
    "dissent note exception detached",
    "unresolved branch closure boundary exception detached",
    "make multilingual_medical_intelligence_cross_language_reviewer_closeout_ledger_reconciliation_exception_controls",
    "reviewer closeout ledger reconciliation exception report",
    "Multilingual Medical Intelligence cross language reviewer closeout ledger reconciliation exception replay controls",
    "Multilingual Medical Intelligence cross language reviewer closeout ledger reconciliation exception replay report",
    "Multilingual Medical Intelligence cross language reviewer closeout ledger reconciliation exception replay data",
    "Multilingual Medical Intelligence cross language reviewer closeout ledger reconciliation exception replay scorer",
    "Multilingual Medical Intelligence cross language reviewer closeout ledger reconciliation exception replay validator",
    "source closeout id exception replay lost",
    "exported ledger row id exception replay lost",
    "owner final state exception replay lost",
    "dissent note exception replay lost",
    "unresolved branch closure boundary exception replay lost",
    "make multilingual_medical_intelligence_cross_language_reviewer_closeout_ledger_reconciliation_exception_replay_controls",
    "reviewer closeout ledger reconciliation exception replay report",
    "reviewer closeout ledger reconciliation exception replay closeout report",
    "make multilingual_medical_intelligence_cross_language_reviewer_closeout_ledger_reconciliation_exception_replay_closeout_controls",
    "unresolved branch closure boundary exception replay closeout lost",
    "dissent note exception replay closeout lost",
    "owner final state exception replay closeout lost",
    "exported ledger row id exception replay closeout lost",
    "source closeout id exception replay closeout lost",
    "Multilingual Medical Intelligence cross language reviewer closeout ledger reconciliation exception replay closeout validator",
    "Multilingual Medical Intelligence cross language reviewer closeout ledger reconciliation exception replay closeout scorer",
    "Multilingual Medical Intelligence cross language reviewer closeout ledger reconciliation exception replay closeout data",
    "Multilingual Medical Intelligence cross language reviewer closeout ledger reconciliation exception replay closeout report",
    "Multilingual Medical Intelligence cross language reviewer closeout ledger reconciliation exception replay closeout controls",
    "reviewer closeout ledger reconciliation exception replay archive report",
    "make multilingual_medical_intelligence_cross_language_reviewer_closeout_ledger_reconciliation_exception_replay_archive_controls",
    "unresolved branch closure boundary exception replay archive lost",
    "dissent note exception replay archive lost",
    "owner final state exception replay archive lost",
    "exported ledger row id exception replay archive lost",
    "source closeout id exception replay archive lost",
    "Multilingual Medical Intelligence cross language reviewer closeout ledger reconciliation exception replay archive validator",
    "Multilingual Medical Intelligence cross language reviewer closeout ledger reconciliation exception replay archive scorer",
    "Multilingual Medical Intelligence cross language reviewer closeout ledger reconciliation exception replay archive data",
    "Multilingual Medical Intelligence cross language reviewer closeout ledger reconciliation exception replay archive report",
    "Multilingual Medical Intelligence cross language reviewer closeout ledger reconciliation exception replay archive controls",
    "Multilingual Medical Intelligence cross language reviewer closeout ledger reconciliation exception replay archive rollup controls",
    "Multilingual Medical Intelligence cross language reviewer closeout ledger reconciliation exception replay archive rollup report",
    "Multilingual Medical Intelligence cross language reviewer closeout ledger reconciliation exception replay archive rollup data",
    "Multilingual Medical Intelligence cross language reviewer closeout ledger reconciliation exception replay archive rollup scorer",
    "Multilingual Medical Intelligence cross language reviewer closeout ledger reconciliation exception replay archive rollup validator",
    "make multilingual_medical_intelligence_cross_language_reviewer_closeout_ledger_reconciliation_exception_replay_archive_rollup_controls",
    "source closeout id exception replay archive rollup lost",
    "exported ledger row id exception replay archive rollup lost",
    "owner final state exception replay archive rollup lost",
    "dissent note exception replay archive rollup lost",
    "unresolved branch closure boundary exception replay archive rollup lost",
    "archive snapshot exception replay archive rollup lost",
    "archive reopenability exception replay archive rollup lost",
    "reviewer closeout ledger reconciliation exception replay archive rollup report",
    "Multilingual Medical Intelligence cross language reviewer closeout ledger reconciliation exception replay archive rollup release controls",
    "Multilingual Medical Intelligence cross language reviewer closeout ledger reconciliation exception replay archive rollup release report",
    "Multilingual Medical Intelligence cross language reviewer closeout ledger reconciliation exception replay archive rollup release data",
    "Multilingual Medical Intelligence cross language reviewer closeout ledger reconciliation exception replay archive rollup release scorer",
    "Multilingual Medical Intelligence cross language reviewer closeout ledger reconciliation exception replay archive rollup release validator",
    "make multilingual_medical_intelligence_cross_language_reviewer_closeout_ledger_reconciliation_exception_replay_archive_rollup_release_controls",
    "source closeout id exception replay archive rollup release lost",
    "exported ledger row id exception replay archive rollup release lost",
    "owner final state exception replay archive rollup release lost",
    "dissent note exception replay archive rollup release lost",
    "unresolved branch closure boundary exception replay archive rollup release lost",
    "archive snapshot exception replay archive rollup release lost",
    "archive reopenability exception replay archive rollup release lost",
    "reviewer closeout ledger reconciliation exception replay archive rollup release report",
    "Multilingual Medical Intelligence cross language reviewer closeout ledger reconciliation exception replay archive rollup release handoff controls",
    "Multilingual Medical Intelligence cross language reviewer closeout ledger reconciliation exception replay archive rollup release handoff report",
    "Multilingual Medical Intelligence cross language reviewer closeout ledger reconciliation exception replay archive rollup release handoff data",
    "Multilingual Medical Intelligence cross language reviewer closeout ledger reconciliation exception replay archive rollup release handoff scorer",
    "Multilingual Medical Intelligence cross language reviewer closeout ledger reconciliation exception replay archive rollup release handoff validator",
    "make multilingual_medical_intelligence_cross_language_reviewer_closeout_ledger_reconciliation_exception_replay_archive_rollup_release_handoff_controls",
    "source closeout id exception replay archive rollup release handoff lost",
    "exported ledger row id exception replay archive rollup release handoff lost",
    "owner final state exception replay archive rollup release handoff lost",
    "dissent note exception replay archive rollup release handoff lost",
    "unresolved branch closure boundary exception replay archive rollup release handoff lost",
    "archive snapshot exception replay archive rollup release handoff lost",
    "archive reopenability exception replay archive rollup release handoff lost",
    "reviewer closeout ledger reconciliation exception replay archive rollup release handoff report",
    "Multilingual Medical Intelligence cross language reviewer closeout ledger reconciliation exception replay archive rollup release handoff closure controls",
    "Multilingual Medical Intelligence cross language reviewer closeout ledger reconciliation exception replay archive rollup release handoff closure report",
    "Multilingual Medical Intelligence cross language reviewer closeout ledger reconciliation exception replay archive rollup release handoff closure data",
    "Multilingual Medical Intelligence cross language reviewer closeout ledger reconciliation exception replay archive rollup release handoff closure scorer",
    "Multilingual Medical Intelligence cross language reviewer closeout ledger reconciliation exception replay archive rollup release handoff closure validator",
    "make multilingual_medical_intelligence_cross_language_reviewer_closeout_ledger_reconciliation_exception_replay_archive_rollup_release_handoff_closure_controls",
    "source closeout id exception replay archive rollup release handoff closure lost",
    "exported ledger row id exception replay archive rollup release handoff closure lost",
    "owner final state exception replay archive rollup release handoff closure lost",
    "dissent note exception replay archive rollup release handoff closure lost",
    "unresolved branch closure boundary exception replay archive rollup release handoff closure lost",
    "archive snapshot exception replay archive rollup release handoff closure lost",
    "archive reopenability exception replay archive rollup release handoff closure lost",
    "reviewer closeout ledger reconciliation exception replay archive rollup release handoff closure report",
    "Multilingual Medical Intelligence cross language reviewer closeout ledger reconciliation exception replay archive rollup release handoff closure archive controls",
    "Multilingual Medical Intelligence cross language reviewer closeout ledger reconciliation exception replay archive rollup release handoff closure archive report",
    "Multilingual Medical Intelligence cross language reviewer closeout ledger reconciliation exception replay archive rollup release handoff closure archive data",
    "Multilingual Medical Intelligence cross language reviewer closeout ledger reconciliation exception replay archive rollup release handoff closure archive scorer",
    "Multilingual Medical Intelligence cross language reviewer closeout ledger reconciliation exception replay archive rollup release handoff closure archive validator",
    "make multilingual_medical_intelligence_cross_language_reviewer_closeout_ledger_reconciliation_exception_replay_archive_rollup_release_handoff_closure_archive_controls",
    "source closeout id exception replay archive rollup release handoff closure archive lost",
    "exported ledger row id exception replay archive rollup release handoff closure archive lost",
    "owner final state exception replay archive rollup release handoff closure archive lost",
    "dissent note exception replay archive rollup release handoff closure archive lost",
    "unresolved branch closure boundary exception replay archive rollup release handoff closure archive lost",
    "archive snapshot exception replay archive rollup release handoff closure archive lost",
    "archive reopenability exception replay archive rollup release handoff closure archive lost",
    "reviewer closeout ledger reconciliation exception replay archive rollup release handoff closure archive report",
    "Multilingual Medical Intelligence cross language reviewer closeout ledger reconciliation exception replay archive rollup release handoff closure archive reuse controls",
    "Multilingual Medical Intelligence cross language reviewer closeout ledger reconciliation exception replay archive rollup release handoff closure archive reuse report",
    "Multilingual Medical Intelligence cross language reviewer closeout ledger reconciliation exception replay archive rollup release handoff closure archive reuse data",
    "Multilingual Medical Intelligence cross language reviewer closeout ledger reconciliation exception replay archive rollup release handoff closure archive reuse scorer",
    "Multilingual Medical Intelligence cross language reviewer closeout ledger reconciliation exception replay archive rollup release handoff closure archive reuse validator",
    "make multilingual_medical_intelligence_cross_language_reviewer_closeout_ledger_reconciliation_exception_replay_archive_rollup_release_handoff_closure_archive_reuse_controls",
    "source closeout id exception replay archive rollup release handoff closure archive reuse lost",
    "exported ledger row id exception replay archive rollup release handoff closure archive reuse lost",
    "owner final state exception replay archive rollup release handoff closure archive reuse lost",
    "dissent note exception replay archive rollup release handoff closure archive reuse lost",
    "unresolved branch closure boundary exception replay archive rollup release handoff closure archive reuse lost",
    "archive snapshot exception replay archive rollup release handoff closure archive reuse lost",
    "archive reopenability exception replay archive rollup release handoff closure archive reuse lost",
    "reviewer closeout ledger reconciliation exception replay archive rollup release handoff closure archive reuse report",
    "forty eight atlas nodes",
    "reviewer decision rationale map shape",
    "make multilingual_medical_intelligence_cross_language_reviewer_decision_rationale_controls",
    "six reviewer decision rationale signal types",
    "reviewer decision rationale signal counts",
    "reviewer decision rationale report",
    "six source recency applicability signal types",
    "make multilingual_medical_intelligence_rewrite_candidate_drift_scorer",
    "MMI 036 closure archive controls",
    "MMI 036 closure archive report",
    "make mmi_036_closure_archive_controls",
    "source closeout id exception replay archive rollup release handoff closure archive reuse release handoff closure archive reuse release handoff closure archive lost",
    "reviewer closeout ledger reconciliation exception replay archive rollup release handoff closure archive reuse release handoff closure archive reuse release handoff closure archive report",
    "MMI 037 closure archive reuse controls",
    "MMI 037 closure archive reuse report",
    "make mmi_037_closure_archive_reuse_controls",
    "source closeout id exception replay archive rollup release handoff closure archive reuse lost",
    "reviewer closeout ledger reconciliation exception replay archive rollup release handoff closure archive reuse report",
    "MMI 038 closure archive reuse release controls",
    "MMI 038 closure archive reuse release report",
    "make mmi_038_closure_archive_reuse_release_controls",
    "source closeout id exception replay archive rollup release handoff closure archive reuse release lost",
    "reviewer closeout ledger reconciliation exception replay archive rollup release handoff closure archive reuse release report",
    "external publication clearance absence",
    "make medical_intelligence_atlas",
    "make multilingual_medical_intelligence_source_check",
    "make multilingual_medical_intelligence_public_wording_bank",
    "checks passing rows, expected fail drift controls, drift signal counts, failure reason counts, reviewer triage, rewrite candidate scoring, blocked candidate counts, cross language ambiguity controls, cross language negation audience controls, cross language scope anchor controls, cross language temporal progression controls, cross language uncertainty calibration controls, cross language source support scope reconciliation controls, cross language source recency applicability controls, cross language source conflict provenance controls, cross language reviewer conflict triage controls, cross language reviewer decision rationale controls, cross language reviewer handoff packet controls, cross language reviewer handoff replay controls, cross language reviewer replay audit trail controls, cross language reviewer replay audit trail closeout controls, cross language reviewer closeout ledger export controls, cross language reviewer closeout ledger reconciliation controls, cross language reviewer closeout ledger reconciliation exception controls, cross language reviewer closeout ledger reconciliation exception replay controls, cross language reviewer closeout ledger reconciliation exception replay closeout controls, cross language reviewer closeout ledger reconciliation exception replay archive controls, cross language reviewer closeout ledger reconciliation exception replay archive rollup controls, cross language reviewer closeout ledger reconciliation exception replay archive rollup release controls, cross language reviewer closeout ledger reconciliation exception replay archive rollup release handoff controls, cross language reviewer closeout ledger reconciliation exception replay archive rollup release handoff closure controls, cross language reviewer closeout ledger reconciliation exception replay archive rollup release handoff closure archive controls, cross language reviewer closeout ledger reconciliation exception replay archive rollup release handoff closure archive reuse controls, cross language reviewer closeout ledger reconciliation exception replay archive rollup release handoff closure archive reuse release controls, cross language reviewer closeout ledger reconciliation exception replay archive rollup release handoff closure archive reuse release handoff controls, cross language reviewer closeout ledger reconciliation exception replay archive rollup release handoff closure archive reuse release handoff closure controls, cross language reviewer closeout ledger reconciliation exception replay archive rollup release handoff closure archive reuse release handoff closure archive controls, cross language reviewer closeout ledger reconciliation exception replay archive rollup release handoff closure archive reuse release handoff closure archive reuse controls, cross language reviewer closeout ledger reconciliation exception replay archive rollup release handoff closure archive reuse release handoff closure archive reuse release controls, cross language reviewer closeout ledger reconciliation exception replay archive rollup release handoff closure archive reuse release handoff closure archive reuse release handoff controls, cross language reviewer closeout ledger reconciliation exception replay archive rollup release handoff closure archive reuse release handoff closure archive reuse release handoff closure controls, and translation clearance absence without score certification",
    "multilingual paired state source checks, public wording bank checks, drift negative controls, public wording drift score report, rewrite candidate score report, cross language ambiguity report, cross language negation audience report, cross language scope anchor report, cross language temporal progression report, cross language uncertainty calibration report, cross language source support scope reconciliation report, cross language source recency applicability report, source conflict provenance report, reviewer conflict triage report, reviewer decision rationale report, reviewer handoff packet report, reviewer handoff replay report, reviewer replay audit trail report, reviewer replay audit trail closeout report, reviewer closeout ledger export report, reviewer closeout ledger reconciliation report, reviewer closeout ledger reconciliation exception report, reviewer closeout ledger reconciliation exception replay report, reviewer closeout ledger reconciliation exception replay closeout report, reviewer closeout ledger reconciliation exception replay archive report, reviewer closeout ledger reconciliation exception replay archive rollup report, reviewer closeout ledger reconciliation exception replay archive rollup release report, reviewer closeout ledger reconciliation exception replay archive rollup release handoff report, reviewer closeout ledger reconciliation exception replay archive rollup release handoff closure report, reviewer closeout ledger reconciliation exception replay archive rollup release handoff closure archive report, reviewer closeout ledger reconciliation exception replay archive rollup release handoff closure archive reuse report, reviewer closeout ledger reconciliation exception replay archive rollup release handoff closure archive reuse release report, reviewer closeout ledger reconciliation exception replay archive rollup release handoff closure archive reuse release handoff report, reviewer closeout ledger reconciliation exception replay archive rollup release handoff closure archive reuse release handoff closure report, reviewer closeout ledger reconciliation exception replay archive rollup release handoff closure archive reuse release handoff closure archive report, reviewer closeout ledger reconciliation exception replay archive rollup release handoff closure archive reuse release handoff closure archive reuse report, reviewer closeout ledger reconciliation exception replay archive rollup release handoff closure archive reuse release handoff closure archive reuse release report, reviewer closeout ledger reconciliation exception replay archive rollup release handoff closure archive reuse release handoff closure archive reuse release handoff report, reviewer closeout ledger reconciliation exception replay archive rollup release handoff closure archive reuse release handoff closure archive reuse release handoff closure report, MMI 036 closure archive report, MMI 037 closure archive reuse report, MMI 038 closure archive reuse release report, and exact next action state",
    "public navigation and claim hygiene materials only",
    "not submissions, applications, merge decisions",
]

FORBIDDEN_SECTION_PHRASES = [
    "application submitted",
    "partner confirmed",
    "official role granted",
    "clinical validation complete",
    "clinical deployment ready",
    "patient data used",
    "benchmark compatible",
    "score certified",
    "fda authorized",
    "eu compliant",
    "chai certified",
    "medhelm partner",
    "healthbench partner",
    "bridge partner",
    "teknofest finalist",
    "terms accepted",
    "payment completed",
    "accepted contribution",
    "merged contribution",
    "endorsement confirmed",
]


def extract_section(text: str, title: str) -> str:
    pattern = rf"^## {re.escape(title)}\n(?P<body>.*?)(?=^## |\Z)"
    match = re.search(pattern, text, flags=re.MULTILINE | re.DOTALL)
    return match.group(0) if match else ""


def main() -> int:
    errors: list[str] = []
    if not README.exists():
        errors.append("Missing README.md")
        section = ""
    else:
        text = README.read_text(encoding="utf-8")
        section = extract_section(text, SECTION_TITLE)

    if not section:
        errors.append(f"README missing section: {SECTION_TITLE}")

    lower_section = section.lower()
    for phrase in REQUIRED_PHRASES:
        if phrase.lower() not in lower_section:
            errors.append(f"Section missing required phrase: {phrase}")

    for link in REQUIRED_LINKS:
        if link not in section:
            errors.append(f"Section missing required link: {link}")
        if not (ROOT / link).exists():
            errors.append(f"Linked file missing: {link}")

    for phrase in FORBIDDEN_SECTION_PHRASES:
        if phrase in lower_section:
            errors.append(f"Section contains forbidden phrase: {phrase}")

    if errors:
        print("FAIL README current surface links validation")
        for error in errors:
            print(f"- {error}")
        return 1

    print("PASS README current surface links validation")
    print(f"section={SECTION_TITLE}")
    print(f"links={len(REQUIRED_LINKS)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
