#!/usr/bin/env python3
from __future__ import annotations

import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
NOTE = ROOT / "docs" / "PUBLIC_RELEASE_NOTE_V0_1_20260616.md"

REQUIRED_PHRASES = [
    "not clinical advice",
    "not patient data",
    "not clinical deployment",
    "not clinical validation",
    "not a model safety claim",
    "not a model ranking",
    "19 synthetic intake rows",
    "14 Turkish synthetic risk rows",
    "10 risk axes",
    "10 of 10 Failure Atlas taxonomy pattern IDs represented",
    "6 public review states",
    "Clinician review protocol v0.1",
    "19 clinician review queue rows",
    "4 source review rows",
    "Source claim review queue v0.1",
    "12 source claim review queue rows",
    "10 SourceCheckup v0.2 answer examples",
    "11 SourceCheckup contributor examples",
    "3 red flag source locator contributor examples",
    "Health data quality and label audit card v0.1",
    "Label audit reviewer role table v0.1",
    "make label_audit_role_table",
    "4 label audit reviewer roles",
    "5 label audit escalation gate rows",
    "1 label audit public contributor issue route",
    "5 label audit example intake rows",
    "5 label audit example dashboard rows",
    "5 label audit maintainer triage rows",
    "5 label audit public wording decision rows",
    "5 label audit release gate rows",
    "5 label audit release gate outcome rows",
    "7 label audit release note packet rows",
    "8 label audit public changelog rows",
    "9 label audit public release index surface rows",
    "10 label audit issue history rows",
    "5 label audit public contributor digest rows",
    "5 label audit maintainer handoff rows",
    "5 label audit maintainer closeout digest rows",
    "5 label audit maintainer release readiness digest rows",
    "5 label audit maintainer evidence map rows",
    "5 label audit maintainer audit trail packet rows",
    "5 label audit maintainer release candidate summary rows",
    "5 label audit maintainer public preview decision rows",
    "5 label audit maintainer public preview handoff rows",
    "5 label audit maintainer public preview closure rows",
    "5 BİLGE readiness queue rows",
    "5 TÜBİTAK 1711 collaboration readiness packet rows",
    "5 SourceCheckup Turkish institutional wording examples",
    "6 SourceCheckup repo run guide rows",
    "6 HealthBench and MedHELM mapping rows",
    "8 benchmark style reviewer question rows",
    "2 reviewer question issue templates",
    "4 reviewer question intake example rows",
    "4 reviewer question intake triage rows",
    "4 reviewer question public wording decision rows",
    "4 reviewer question release gate rows",
    "4 reviewer question release gate outcome rows",
    "7 reviewer question public release packet rows",
    "8 reviewer question public changelog rows",
    "9 reviewer question public release index surface rows",
    "11 reviewer question issue history rows",
    "5 reviewer question public contributor digest rows",
    "5 reviewer question maintainer handoff rows",
    "5 reviewer question maintainer closeout digest rows",
    "5 reviewer question maintainer release readiness digest rows",
    "5 reviewer question maintainer evidence map rows",
    "5 reviewer question maintainer audit trail packet rows",
    "5 reviewer question maintainer release candidate summary rows",
    "5 reviewer question maintainer public preview decision rows",
    "5 reviewer question maintainer public preview handoff rows",
    "5 reviewer question maintainer public preview closure rows",
    "5 reviewer question maintainer public preview archive rows",
    "Label audit example intake v0.1",
    "Label audit example dashboard v0.1",
    "Label audit maintainer triage board v0.1",
    "Label audit public wording decision log v0.1",
    "Label audit release gate checklist v0.1",
    "Label audit release gate outcome dashboard v0.1",
    "Label audit release note packet v0.1",
    "Label audit public changelog v0.1",
    "Label audit public release index v0.1",
    "Label audit public contributor digest v0.1",
    "Label audit maintainer handoff notes v0.1",
    "Label audit maintainer closeout digest v0.1",
    "Label audit maintainer release readiness digest v0.1",
    "Label audit maintainer evidence map v0.1",
    "Label audit maintainer audit trail packet v0.1",
    "Label audit maintainer release candidate summary v0.1",
    "Label audit maintainer public preview decision log v0.1",
    "Label audit maintainer public preview handoff summary v0.1",
    "Label audit maintainer public preview closure checklist v0.1",
    "BİLGE readiness queue v0.1",
    "TÜBİTAK 1711 collaboration readiness packet v0.1",
    "SourceCheckup Turkish institutional wording examples v0.1",
    "SourceCheckup repo run guide v0.1",
    "HealthBench and MedHELM mapping note v0.1",
    "Benchmark style reviewer questions v0.1",
    "Contributor issue template reviewer questions v0.1",
    "Reviewer question intake examples v0.1",
    "Reviewer question intake triage board v0.1",
    "Reviewer question public wording decision log v0.1",
    "Reviewer question release gate checklist v0.1",
    "Reviewer question release gate outcome dashboard v0.1",
    "Reviewer question public release packet v0.1",
    "Reviewer question public changelog v0.1",
    "Reviewer question public release index v0.1",
    "Reviewer question public contributor digest v0.1",
    "Reviewer question maintainer handoff notes v0.1",
    "Reviewer question maintainer closeout digest v0.1",
    "Reviewer question maintainer release readiness digest v0.1",
    "Reviewer question maintainer evidence map v0.1",
    "Reviewer question maintainer audit trail packet v0.1",
    "Reviewer question maintainer release candidate summary v0.1",
    "Reviewer question maintainer public preview decision log v0.1",
    "Reviewer question maintainer public preview handoff summary v0.1",
    "Reviewer question maintainer public preview closure checklist v0.1",
    "Reviewer question maintainer public preview archive digest v0.1",
    "Reviewer question maintainer public preview index rollup v0.1",
    "Reviewer question maintainer public preview repository navigation note v0.1",
    "Reviewer question maintainer public preview release card v0.1",
    "Reviewer question maintainer public preview contributor route note v0.1",
    "Reviewer question maintainer public preview issue template route note v0.1",
    "make bilge_readiness_queue",
    "make tubitak_1711_readiness_packet",
    "make sourcecheckup_turkish_institutional_wording",
    "make sourcecheckup_repo_run_guide",
    "make healthbench_medhelm_mapping",
    "make benchmark_reviewer_questions",
    "make reviewer_question_issue_templates",
    "make reviewer_question_maintainer_public_preview_index_rollup",
    "make reviewer_question_maintainer_public_preview_repository_navigation_note",
    "make reviewer_question_maintainer_public_preview_release_card",
    "make reviewer_question_maintainer_public_preview_contributor_route_note",
    "make reviewer_question_maintainer_public_preview_issue_template_route_note",
    "make reviewer_question_intake_examples",
    "make reviewer_question_intake_triage",
    "make reviewer_question_wording_log",
    "make reviewer_question_release_gates",
    "make reviewer_question_gate_outcomes",
    "make reviewer_question_release_packet",
    "make reviewer_question_changelog",
    "make reviewer_question_release_index",
    "make reviewer_question_contributor_digest",
    "make reviewer_question_maintainer_handoff",
    "make reviewer_question_maintainer_closeout_digest",
    "make reviewer_question_maintainer_release_readiness_digest",
    "make reviewer_question_maintainer_evidence_map",
    "make reviewer_question_maintainer_audit_trail_packet",
    "make label_audit_examples",
    "make label_audit_dashboard",
    "make label_audit_triage",
    "make label_audit_wording_log",
    "make label_audit_release_gates",
    "make label_audit_outcome_dashboard",
    "make label_audit_release_packet",
    "make label_audit_changelog",
    "make label_audit_release_index",
    "make label_audit_contributor_digest",
    "make label_audit_maintainer_handoff",
    "make label_audit_maintainer_closeout_digest",
    "make label_audit_maintainer_release_readiness_digest",
    "synthetic label audit example intake rows for provenance, label definition, pilot subset, raw output exclusion, and dataset quality proof boundaries",
    "compact label audit example dashboard that summarizes role, audit row, review state, and blocked public claim type",
    "label audit maintainer triage board that turns dashboard rows into maintainer actions and public wording decisions",
    "label audit public wording decision log that records blocked wording and proposed public wording",
    "label audit release gate checklist that converts wording decisions into pass or block release states",
    "label audit release gate outcome dashboard that summarizes pass and block outcomes",
    "label audit release note packet that packages the label audit public release surfaces",
    "label audit public changelog that records the chronological maintainer sequence",
    "label audit public release index that consolidates the label audit route and issue history",
    "label audit public contributor digest that gives contributors a short orientation path",
    "label audit maintainer closeout digest that gives maintainers a compact closeout trail",
    "label audit maintainer release readiness digest that gives maintainers a public preview readiness trail",
    "label audit maintainer evidence map that traces readiness rows to public evidence surfaces",
    "label audit maintainer audit trail packet that traces evidence rows to public audit trail surfaces",
    "label audit maintainer release candidate summary that records the current public preview candidate state",
    "label audit maintainer public preview decision log that records current public preview decision rows",
    "label audit maintainer public preview handoff summary that turns current public preview decisions into reviewer actions",
    "label audit maintainer public preview closure checklist that turns reviewer actions into closeable public preview checks",
    "Label audit public contributor issue guide v0.1",
    "make label_audit_public_issue",
    "public label audit contributor issue route for synthetic data quality and label audit review examples",
    "Label audit reviewer role table that assigns provenance, label definition, pilot subset, and public release boundary review roles",
    "Label audit escalation gate rows for synthetic provenance, label definition lock, pilot inter rater subset, raw output exclusion, and public release boundaries",
    "label audit release gate checklist that makes public release decisions reproducible for synthetic dataset review",
    "label audit release gate outcome dashboard that makes current pass and block states inspectable for maintainers",
    "label audit release note packet that gives maintainers one public summary surface for the whole label audit route",
    "label audit public changelog that makes the label audit release sequence inspectable for contributors",
    "label audit public release index that gives contributors one entry point for route, packet, changelog, commands, and issue history",
    "label audit public contributor digest that turns the release index into a compact contributor path",
    "label audit maintainer handoff notes that give maintainers a closeout checklist",
    "label audit maintainer handoff notes that turn contributor proposals into bounded maintainer actions",
    "label audit maintainer closeout digest that records current public preview closeout rows",
    "label audit maintainer release readiness digest that records current public preview readiness rows",
    "label audit maintainer evidence map that records current public preview evidence rows",
    "label audit maintainer audit trail packet that records current public preview audit trail rows",
    "label audit maintainer release candidate summary that records current public preview candidate rows",
    "label audit maintainer public preview decision log that records current public preview decision rows",
    "label audit maintainer public preview handoff summary that records current public preview reviewer actions",
    "label audit maintainer public preview closure checklist that records current public preview closure checks",
    "BİLGE readiness queue that records no access, no score, and no endorsement preparation steps",
    "BİLGE readiness queue pattern for model readiness without access, ranking, score, safety, benchmark compatibility, or endorsement claims",
    "TÜBİTAK 1711 collaboration readiness packet that records no submission, no application, no funding, no partner, no health priority, no route access, and no endorsement preparation boundaries",
    "TÜBİTAK 1711 collaboration readiness packet pattern for public collaboration preparation without submission, funding, partner, route access, or endorsement claims",
    "SourceCheckup Turkish institutional wording examples",
    "endorsement, route access, submission, deployment, and validation wording",
    "SourceCheckup repo run guide that gives one runnable path and doctor checks for required files and row counts",
    "without external calls, model calls, patient data, source truth certification, or clinical validation claims",
    "HealthBench and MedHELM mapping note that connects six local public surfaces to source anchored benchmark vocabulary without compatibility, ranking, validation, deployment, or endorsement claims",
    "HealthBench and MedHELM mapping note for benchmark maintainer readability without compatibility, equivalence, ranking, score, clinical deployment, clinical validation, or endorsement claims",
    "Benchmark style reviewer questions that turn SourceCheckup and Failure Atlas rows into public questions for source support, escalation, medication safety, missing context, policy wording, and warning sign visibility without scoring or compatibility claims",
    "Benchmark style reviewer questions for public contributor review without scoring, ranking, endpoint calls, patient data, compatibility claims, clinical validation, or endorsement claims",
    "Contributor issue template reviewer questions that add benchmark reviewer question fields to SourceCheckup and Failure Atlas public issue templates without scoring or compatibility claims",
    "Contributor issue template reviewer questions for public intake without scoring, ranking, endpoint calls, patient data, compatibility claims, clinical validation, or endorsement claims",
    "Reviewer question intake examples that connect synthetic SourceCheckup and Failure Atlas template fields to benchmark reviewer question ids without scoring, compatibility, endpoint, patient data, clinical validation, or endorsement claims",
    "Reviewer question intake examples for public intake orientation without scoring, ranking, endpoint calls, patient data, compatibility claims, clinical validation, or endorsement claims",
    "Reviewer question intake triage board that maps intake examples to maintainer actions, owner roles, review states, and public wording decisions without scoring, compatibility, endpoint, patient data, clinical validation, or endorsement claims",
    "Reviewer question intake triage board for maintainer review without scoring, ranking, endpoint calls, patient data, compatibility claims, clinical validation, or endorsement claims",
    "Reviewer question public wording decision log that records blocked wording and proposed public wording for source support, policy wording, escalation, and medication safety rows without scoring, compatibility, endpoint, patient data, clinical validation, or endorsement claims",
    "Reviewer question public wording decision log for maintainer wording review without scoring, ranking, endpoint calls, patient data, compatibility claims, clinical validation, or endorsement claims",
    "Reviewer question release gate checklist that converts public wording decisions into pass and block states without scoring, compatibility, endpoint, patient data, clinical validation, or endorsement claims",
    "Reviewer question release gate checklist for public preview release decisions without scoring, ranking, endpoint calls, patient data, compatibility claims, clinical validation, or endorsement claims",
    "Reviewer question release gate outcome dashboard that summarizes current pass and block outcomes without scoring, compatibility, endpoint, patient data, clinical validation, or endorsement claims",
    "Reviewer question release gate outcome dashboard for public preview outcome review without scoring, ranking, endpoint calls, patient data, compatibility claims, clinical validation, or endorsement claims",
    "Reviewer question public release packet that packages public reviewer question surfaces without scoring, compatibility, endpoint, patient data, clinical validation, or endorsement claims",
    "Reviewer question public release packet for one maintainer facing release surface without scoring, ranking, endpoint calls, patient data, compatibility claims, clinical validation, or endorsement claims",
    "Reviewer question public changelog that records the chronological public reviewer question sequence without scoring, compatibility, endpoint, patient data, clinical validation, or endorsement claims",
    "Reviewer question public changelog for maintainer chronology without scoring, ranking, endpoint calls, patient data, compatibility claims, clinical validation, or endorsement claims",
    "Reviewer question public release index that gives one public entry point for route, packet, changelog, commands, issue history, and boundaries without scoring, compatibility, endpoint, patient data, clinical validation, or endorsement claims",
    "Reviewer question public release index for one contributor entry point without scoring, ranking, endpoint calls, patient data, compatibility claims, clinical validation, or endorsement claims",
    "Reviewer question public contributor digest for compact contributor orientation without scoring, ranking, endpoint calls, patient data, compatibility claims, clinical validation, or endorsement claims",
    "Reviewer question maintainer handoff notes for bounded maintainer review without scoring, ranking, endpoint calls, patient data, compatibility claims, clinical validation, or endorsement claims",
    "Reviewer question maintainer closeout digest for public preview closeout without scoring, ranking, endpoint calls, patient data, compatibility claims, clinical validation, or endorsement claims",
    "Reviewer question maintainer release readiness digest for public preview readiness without scoring, ranking, endpoint calls, patient data, compatibility claims, clinical validation, or endorsement claims",
    "Reviewer question maintainer evidence map for public preview evidence tracing without scoring, ranking, endpoint calls, patient data, compatibility claims, clinical validation, or endorsement claims",
    "Reviewer question maintainer audit trail packet for public preview audit tracing without scoring, ranking, endpoint calls, patient data, compatibility claims, clinical validation, or endorsement claims",
    "Reviewer question maintainer release candidate summary for public preview candidate review without scoring, ranking, endpoint calls, patient data, compatibility claims, clinical validation, or endorsement claims",
    "Reviewer question maintainer public preview decision log for public preview decisions without scoring, ranking, endpoint calls, patient data, compatibility claims, clinical validation, or endorsement claims",
    "Reviewer question maintainer public preview handoff summary for public preview reviewer actions without scoring, ranking, endpoint calls, patient data, compatibility claims, clinical validation, or endorsement claims",
    "Reviewer question maintainer public preview closure checklist for closeable public preview checks without scoring, ranking, endpoint calls, patient data, compatibility claims, clinical validation, or endorsement claims",
    "Reviewer question maintainer public preview archive digest for compact public preview trace without scoring, ranking, endpoint calls, patient data, compatibility claims, clinical validation, or endorsement claims",
    "Reviewer question maintainer public preview index rollup for one maintainer navigation surface without scoring, ranking, endpoint calls, patient data, compatibility claims, clinical validation, or endorsement claims",
    "Reviewer question maintainer public preview repository navigation note for ordered public preview reading without scoring, ranking, endpoint calls, patient data, compatibility claims, clinical validation, or endorsement claims",
    "Reviewer question maintainer public preview release card for compact public preview positioning without scoring, ranking, endpoint calls, patient data, compatibility claims, clinical validation, or endorsement claims",
    "Reviewer question maintainer public preview contributor route note for public contributor proposal routing without scoring, ranking, endpoint calls, patient data, compatibility claims, clinical validation, or endorsement claims",
    "Reviewer question maintainer public preview issue template route note for public proposal field routing without scoring, ranking, endpoint calls, patient data, compatibility claims, clinical validation, or endorsement claims",
    "benchmark style reviewer questions without scoring or compatibility claims",
    "6 reviewer question maintainer public preview index rollup rows",
    "6 reviewer question maintainer public preview repository navigation rows",
    "6 reviewer question maintainer public preview release card rows",
    "6 reviewer question maintainer public preview contributor route note rows",
    "6 reviewer question maintainer public preview issue template route note rows",
    "Add a reviewer question maintainer public preview maintainer acceptance checklist without scoring or compatibility claims",
    "150 synthetic scenario rows",
    "70 prompt rows",
    "24 pilot inter rater rows",
    "MedHELM and Medmarks boundary notes v0.1",
    "Medical language model assurance card template v0.1",
    "Assurance card template for intended use, risk, source support, human review, and release gate boundaries",
    "SourceCheckup public contributor issue route v0.1",
    "make sourcecheckup_public_issue",
    "public SourceCheckup contributor issue route for synthetic source claim review examples",
    "SourceCheckup source claim example expansion v0.2",
    "make sourcecheckup_expansion_dashboard",
    "generated SourceCheckup expansion dashboard",
    "6 clinician literacy release gate lessons",
    "Clinician literacy release gate lesson map v0.1",
    "make clinician_literacy_map",
    "clinician literacy lesson map that connects Failure Atlas, TR MedLLM, SourceCheckup, assurance gates, and clinician review states",
    "6 assurance release gate examples",
    "Assurance release gate example map v0.1",
    "make assurance_release_gate_map",
    "generated assurance release gate map that connects public examples to assurance card sections and release gate levels",
    "7 SourceCheckup TR MedLLM assurance routes",
    "SourceCheckup TR MedLLM assurance routing map v0.1",
    "make sourcecheckup_tr_medllm_routing",
    "SourceCheckup TR MedLLM assurance routing map that connects 12 source claim queue rows, 14 Turkish synthetic risk rows, and six assurance release gate examples",
    "generated SourceCheckup TR MedLLM assurance routing map that links source surfaces, risk axes, release gate levels, and blocked public wording",
    "2 source review worksheets",
    "Source review worksheets v0.1",
    "make source_review_worksheets",
    "Source review worksheets that turn medication safety and policy wording routes into concrete public review questions",
    "Source review worksheets for medication safety and policy wording without source truth certification or clinical claims",
    "3 red flag warning checklists",
    "4 warning sign reviewer roles",
    "5 escalation gate audit rows",
    "Red flag source locator and warning sign checklist v0.1",
    "make red_flag_warning_checklist",
    "Red flag source locator and warning sign checklist that turns false reassurance, rare danger, and source locator risks into public review steps",
    "Red flag warning checklists for partial negative evidence, symptom fluctuation, and source locator triage claims",
    "Warning sign reviewer role table v0.1",
    "make warning_sign_role_table",
    "Warning sign reviewer role table that assigns clinician, source locator, warning sign wording, and adjudication roles",
    "Escalation gate audit rows for partial negative evidence, symptom fluctuation, source locator triage claims, public wording boundaries, and reviewer disagreement",
    "Red flag source locator contributor examples v0.1",
    "make red_flag_contributor_examples",
    "Red flag source locator contributor examples that turn unsafe red flag wording into SourceCheckup contribution rows",
    "Red flag contributor examples for PMID locator misuse, broad source reassurance, and warning sign placement",
    "Six platform dashboard index v0.1",
    "docs/PLATFORM_DASHBOARD_INDEX_V0_1.md",
    "make platform_dashboard",
    "public dashboard entry point that links the six seed platforms and their runnable checks",
    "TR MedLLM specialty spread dashboard v0.1",
    "make tr_medllm_specialty_dashboard",
    "generated specialty spread dashboard for multilingual medical AI safety benchmark growth",
]

FORBIDDEN_PHRASES = [
    "validated for clinical use",
    "safe for clinical use",
    "approved by",
    "official acceptance",
    "regulatory approval",
    "model is safe",
    "best model",
    "patient data used",
]


def main() -> int:
    errors: list[str] = []
    if not NOTE.exists():
        errors.append(f"Missing release note: {NOTE}")
        text = ""
    else:
        text = NOTE.read_text(encoding="utf-8")
    lower_text = text.lower()

    for phrase in REQUIRED_PHRASES:
        if phrase.lower() not in lower_text:
            errors.append(f"Missing required phrase: {phrase}")

    for phrase in FORBIDDEN_PHRASES:
        if phrase in lower_text:
            errors.append(f"Forbidden phrase present: {phrase}")

    if "```bash" not in text:
        errors.append("Release note should include runnable command block")

    if errors:
        print("FAIL public release note validation")
        for error in errors:
            print(f"- {error}")
        return 1

    print("PASS public release note validation")
    print(f"file={NOTE.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
